Atreyu: Atreyu.ViewModels.CombinedHeatmapViewModel Class Reference
Atreyu.ViewModels.CombinedHeatmapViewModel Class Reference
The combined heatmap view model.
Public Member Functions
CombinedHeatmapViewModel ()
Initializes a new instance of the CombinedHeatmapViewModel class.
double[,] ExportHeatmapDataCompressed ()
The export heatmap data compressed.
IDictionary< double, double > ExportMzDataCompressed ()
The export mz data compressed method.
IDictionary< int, double > ExportTicDataCompressed ()
The export tic data compressed method.
async Task FetchSingleFrame (int frameNumber)
The set up plot method.
Image GetImage ()
The get image method.
async Task InitializeUimfData (string file)
The initialize uimf data.
async void SumFrames (FrameRange sumFrames)
The sum frames.
void UpdateLowGate (double gate)
The update low gate.
async Task ZoomOut ()
The zoom out.
Properties
bool CircularWaitIsVisible [get, set]
Gets or sets a value indicating whether the circular wait is visible.
string CurrentFile [get, set]
Gets or sets the current file.
FrameManipulationViewModel FrameManipulationViewModel [get, set]
Gets the frame manipulation view model.
HeatMapViewModel HeatMapViewModel [get, set]
Gets the heat map view model.
int Height [get, set]
Gets the height of the Heat map plot.
GateSliderViewModel LowValueGateSliderViewModel [get, set]
Gets the low value gate slider view model.
double MzCenter [get, set]
Gets or sets the mz center.
bool MzRangeEnabled [get, set]
Gets or sets a value indicating whether mz range enabled.
MzSpectraViewModel MzSpectraViewModel [get, set]
Gets the mz spectra view model.
double PartsPerMillion [get, set]
Gets or sets the parts per million.
TotalIonChromatogramViewModel TotalIonChromatogramViewModel [get, set]
Gets the total ion chromatogram view model.
UimfData UimfData [get, set]
Gets or sets the data relevant to the UIMF that is loaded.
int Width [get, set]
Gets the width of the Heat map plot.
ReactiveCommand< object > ZoomOutFull [get, set]
Gets the zoom out full.
Private Member Functions
async Task UpdateMzWindow ()
Updates the mz window.
Private Attributes
const bool ReturnGatedData = true
The return gated data bool.
double centerMz = 1000.0D
The center of the m/z window.
bool circularWaitIsVisible
A private backing field for a property that indicates whether The circular wait is visible.
int currentEndFrame
The current end frame.
string currentFile = "Heatmap"
The name of the current file that is loaded, without path or extension.
int currentStartFrame
The current start frame.
int height
The height of the view.
BinRange mzWindow = new BinRange()
The m/z window represented as a BinRange.
double partsPerMillion = 150.0D
The parts per million tolerance for the m/z window.
UimfData uimfData
The uimf data.
int width
The width of the view.
bool windowMz
Whether or not to window the M/Z.
Detailed Description
The combined heatmap view model.
Definition at line 47 of file CombinedHeatmapViewModel.cs.
Constructor & Destructor Documentation
Atreyu.ViewModels.CombinedHeatmapViewModel.CombinedHeatmapViewModel ()
Initializes a new instance of the CombinedHeatmapViewModel class.
Definition at line 122 of file CombinedHeatmapViewModel.cs.
References Atreyu.ViewModels.MzSpectraViewModel.BinToMzMap, Atreyu.ViewModels.HeatMapViewModel.BinToMzMap, Atreyu.ViewModels.MzSpectraViewModel.Calibrator, Atreyu.ViewModels.MzSpectraViewModel.ChangeEndBin(), Atreyu.ViewModels.TotalIonChromatogramViewModel.ChangeEndScan(), Atreyu.ViewModels.MzSpectraViewModel.ChangeStartBin(), Atreyu.ViewModels.TotalIonChromatogramViewModel.ChangeStartScan(), Atreyu.ViewModels.HeatMapViewModel.CurrentBinRange, Atreyu.ViewModels.HeatMapViewModel.CurrentMaxBin, Atreyu.ViewModels.HeatMapViewModel.CurrentMaxScan, Atreyu.ViewModels.HeatMapViewModel.CurrentMinBin, Atreyu.ViewModels.HeatMapViewModel.CurrentMinScan, Atreyu.ViewModels.HeatMapViewModel.CurrentScanRange, Atreyu.ViewModels.HeatMapViewModel.ForceMinMaxMz, Atreyu.ViewModels.FrameManipulationViewModel.FrameType, Atreyu.ViewModels.MzSpectraViewModel.MzArray, Atreyu.ViewModels.MzSpectraViewModel.MzIntensities, Atreyu.ViewModels.MzSpectraViewModel.ShowMz, Atreyu.ViewModels.HeatMapViewModel.UpdateData(), Atreyu.ViewModels.TotalIonChromatogramViewModel.UpdateFrameData(), Atreyu.ViewModels.MzSpectraViewModel.UpdateFrameData(), Atreyu.ViewModels.TotalIonChromatogramViewModel.UpdateReference(), Atreyu.ViewModels.MzSpectraViewModel.UpdateReference(), Atreyu.ViewModels.HeatMapViewModel.UpdateReference(), Atreyu.ViewModels.FrameManipulationViewModel.UpdateUimf(), and Atreyu.ViewModels.MzSpectraViewModel.ValuesPerPixelY.
         {
             // I wonder if I should break this up a little, as it is over 100 lines and breaking them up logically might make it more readable and maintainable
             this.FrameManipulationViewModel = new FrameManipulationViewModel();
             this.HeatMapViewModel = new HeatMapViewModel();
             this.MzSpectraViewModel = new MzSpectraViewModel();
             this.LowValueGateSliderViewModel = new GateSliderViewModel();
             this.TotalIonChromatogramViewModel = new TotalIonChromatogramViewModel();
             this.LowValueGateSliderViewModel.ControlLabel = "Low Gate";
             this.LowValueGateSliderViewModel.UpdateGate(0);
             // Shows loading image
             this.WhenAnyValue(vm => vm.UimfData.LoadingData).Subscribe(x => this.CircularWaitIsVisible = x);
             // Keep the M/Z mode settings updated
             this.WhenAnyValue(vm => vm.MzRangeEnabled)
                 .Where(b => this.UimfData != null)
                 .Subscribe(x => this.UimfData.WindowMz = x);
             this.WhenAnyValue(vm => vm.MzCenter)
                 .Where(b => this.UimfData != null)
                 .Subscribe(x => this.UimfData.MzCenter = x);
             this.WhenAnyValue(vm => vm.PartsPerMillion)
                 .Where(b => this.UimfData != null)
                 .Subscribe(x => this.UimfData.PartsPerMillion = x);
             this.WhenAnyValue(vm => vm.MzRangeEnabled).Subscribe(x => this.HeatMapViewModel.ForceMinMaxMz = x);
             this.WhenAnyValue(vm => vm.MzRangeEnabled, vm => vm.MzCenter, vm => vm.PartsPerMillion)
                 .Where(tuple => tuple.Item1 && this.UimfData != null)
                 .Select(async _ => await this.UpdateMzWindow())
                 .Subscribe();
             this.ZoomOutFull = this.FrameManipulationViewModel.ZoomOutCommand;
             this.ZoomOutFull.Select(async _ => await this.ZoomOut()).Subscribe();
             // update the uimf data for the various components
             this.WhenAnyValue(vm => vm.UimfData).Subscribe(this.TotalIonChromatogramViewModel.UpdateReference);
             this.WhenAnyValue(vm => vm.UimfData).Subscribe(this.HeatMapViewModel.UpdateReference);
             this.WhenAnyValue(vm => vm.UimfData).Subscribe(this.FrameManipulationViewModel.UpdateUimf);
             this.WhenAnyValue(vm => vm.UimfData).Subscribe(this.MzSpectraViewModel.UpdateReference);
             // update the frame data of the TIC plot when needed; apparently the Throttler should always specify the schedule.
             this.WhenAnyValue(vm => vm.UimfData.GatedFrameData)
                 .Subscribe(this.TotalIonChromatogramViewModel.UpdateFrameData);
             // Update the Framedata of the M/Z plot when needed
             this.WhenAnyValue(vm => vm.UimfData.GatedFrameData).Subscribe(this.MzSpectraViewModel.UpdateFrameData);
             this.WhenAnyValue(vm => vm.UimfData.GatedFrameData).Subscribe(this.HeatMapViewModel.UpdateData);
             // update the frame whenever it is changed via the frame manipulation view
             this.WhenAnyValue(vm => vm.FrameManipulationViewModel.CurrentFrame)
                 .Select(async x => await this.FetchSingleFrame(x))
                 .Subscribe();
             // hook up the frame summing feature
             this.WhenAnyValue(vm => vm.FrameManipulationViewModel.Range).Subscribe(this.SumFrames);
             // These make the axis on the TIC update properly
             this.WhenAnyValue(vm => vm.UimfData.StartScan).Subscribe(this.TotalIonChromatogramViewModel.ChangeStartScan);
             this.WhenAnyValue(vm => vm.UimfData.EndScan).Subscribe(this.TotalIonChromatogramViewModel.ChangeEndScan);
             // These make the axis on the mz plot update properly
             this.WhenAnyValue(vm => vm.UimfData.CurrentMinBin).Subscribe(this.MzSpectraViewModel.ChangeStartBin);
             this.WhenAnyValue(vm => vm.UimfData.CurrentMaxBin).Subscribe(this.MzSpectraViewModel.ChangeEndBin);
             // Update the Heatmap axes
             this.WhenAnyValue(vm => vm.UimfData.StartScan).Subscribe(i => this.HeatMapViewModel.CurrentMinScan = i);
             this.WhenAnyValue(vm => vm.UimfData.EndScan).Subscribe(i => this.HeatMapViewModel.CurrentMaxScan = i);
             this.WhenAnyValue(vm => vm.UimfData.CurrentMinBin).Subscribe(i => this.HeatMapViewModel.CurrentMinBin = i);
             this.WhenAnyValue(vm => vm.UimfData.CurrentMaxBin).Subscribe(i => this.HeatMapViewModel.CurrentMaxBin = i);
             // This makes the axis of the mz plot be in mz mode properly
             this.WhenAnyValue(vm => vm.FrameManipulationViewModel.MzModeEnabled)
                 .Subscribe(b => this.MzSpectraViewModel.ShowMz = b);
             // These two allow the mz calculation to be done on the fly so it is fast, instead of calling the hard drive again
             this.WhenAnyValue(vm => vm.UimfData.FrameSlope)
                 .Where(b => this.UimfData != null)
                 .Subscribe(d => this.MzSpectraViewModel.Slope = d);
             this.WhenAnyValue(vm => vm.UimfData.FrameIntercept)
                 .Where(b => this.UimfData != null)
                 .Subscribe(d => this.MzSpectraViewModel.Intercept = d);
             // Attach the heatmap threshold to the slider's gate, using Throttle so it doesn't seem jerky.
             this.WhenAnyValue(vm => vm.LowValueGateSliderViewModel.LogarithmicGate)
                 .Where(b => this.UimfData != null)
                 .Throttle(TimeSpan.FromMilliseconds(50), RxApp.MainThreadScheduler)
                 .Subscribe(this.UpdateLowGate);
             // Update the frame type on the Fram Manipulation view
             this.WhenAnyValue(vm => vm.UimfData.FrameType).Subscribe(s => this.FrameManipulationViewModel.FrameType = s);
             // update the values per pixel so that the m/z adjusts correctly
             this.WhenAnyValue(vm => vm.UimfData.ValuesPerPixelY)
                 .Subscribe(d => this.MzSpectraViewModel.ValuesPerPixelY = d);
             this.WhenAnyValue(vm => vm.UimfData.BinToMzMap).Subscribe(d => this.MzSpectraViewModel.BinToMzMap = d);
             this.WhenAnyValue(vm => vm.UimfData.MzArray).Subscribe(d => this.MzSpectraViewModel.MzArray = d);
             this.WhenAnyValue(vm => vm.UimfData.MzIntensities).Subscribe(i => this.MzSpectraViewModel.MzIntensities = i);
             this.WhenAnyValue(vm => vm.UimfData.BinToMzMap).Subscribe(d => this.HeatMapViewModel.BinToMzMap = d);
             this.WhenAnyValue(vm => vm.UimfData.Calibrator).Subscribe(c => this.MzSpectraViewModel.Calibrator = c);
             this.WhenAnyValue(vm => vm.HeatMapViewModel.Height).Subscribe(d => this.Height = d);
             this.WhenAnyValue(vm => vm.HeatMapViewModel.Width).Subscribe(d => this.Width = d);
             this.HeatMapViewModel.WhenAnyValue(hm => hm.CurrentBinRange)
                 .Where(_ => this.UimfData != null && this.HeatMapViewModel.CurrentBinRange != null)
                 .Select(
                     async x =>
{
                             this.UimfData.RangeUpdateList.Enqueue(x);
                             await this.uimfData.CheckQueue();
                         }).Subscribe();
             this.HeatMapViewModel.WhenAnyValue(hm => hm.CurrentScanRange)
                 .Where(_ => this.UimfData != null && this.HeatMapViewModel.CurrentScanRange != null)
                 .Select(
                     async x =>
{
                             this.UimfData.RangeUpdateList.Enqueue(x);
                             await this.uimfData.CheckQueue();
                         }).Subscribe();
         }
Member Function Documentation
double [,] Atreyu.ViewModels.CombinedHeatmapViewModel.ExportHeatmapDataCompressed ()
The export heatmap data compressed.
Returns
The 2d array of doubles that represents that data in the view.
Definition at line 426 of file CombinedHeatmapViewModel.cs.
         {
             return this.HeatMapViewModel.GetCompressedDataInView();
         }
IDictionary<double, double> Atreyu.ViewModels.CombinedHeatmapViewModel.ExportMzDataCompressed ()
The export mz data compressed method.
Returns
The dictionary of data, keyed by mz.
Definition at line 437 of file CombinedHeatmapViewModel.cs.
         {
             return this.MzSpectraViewModel.GetMzDataCompressed();
         }
IDictionary<int, double> Atreyu.ViewModels.CombinedHeatmapViewModel.ExportTicDataCompressed ()
The export tic data compressed method.
Returns
The dictionary of data, keyed by scan.
Definition at line 448 of file CombinedHeatmapViewModel.cs.
         {
             return this.TotalIonChromatogramViewModel.GetTicData();
         }
async Task Atreyu.ViewModels.CombinedHeatmapViewModel.FetchSingleFrame (int frameNumber)
The set up plot method.
Parameters
frameNumber The frame number to load.
Returns
The Task.
Definition at line 462 of file CombinedHeatmapViewModel.cs.
         {
             this.currentStartFrame = frameNumber;
             this.currentEndFrame = frameNumber;
             await
                 this.UimfData.ReadData(
                     1,
                     this.UimfData.MaxBins,
                     frameNumber,
                     frameNumber,
                     this.Height,
                     this.Width,
                     0,
                     this.UimfData.Scans,
                     ReturnGatedData);
         }
Image Atreyu.ViewModels.CombinedHeatmapViewModel.GetImage ()
The get image method.
Returns
The Image of the current three plots in view.
Definition at line 486 of file CombinedHeatmapViewModel.cs.
         {
             var tic = this.TotalIonChromatogramViewModel.GetTicImage();
             var mz = this.MzSpectraViewModel.GetMzImage();
             var heatmap = this.HeatMapViewModel.GetHeatmapImage();
             const int Alignment = 25;
             var bitmap = new Bitmap(mz.Width + heatmap.Width, heatmap.Height + tic.Height + Alignment);
             using (var g = Graphics.FromImage(bitmap))
             {
                 g.DrawImage(mz, 0, 0);
                 g.DrawImage(heatmap, mz.Width, Alignment);
                 g.DrawImage(tic, mz.Width, heatmap.Height + Alignment);
             }
             return bitmap;
         }
async Task Atreyu.ViewModels.CombinedHeatmapViewModel.InitializeUimfData (string file)
The initialize uimf data.
Parameters
file The file.
Returns
The Task.
Definition at line 513 of file CombinedHeatmapViewModel.cs.
         {
             if (string.IsNullOrWhiteSpace(file))
             {
                 return;
             }
             this.UimfData = new UimfData(file) { CurrentMinBin = 0 };
             this.UimfData.CurrentMaxBin = this.UimfData.TotalBins;
             await this.FetchSingleFrame(1);
             this.CurrentFile = Path.GetFileNameWithoutExtension(file);
             this.HeatMapViewModel.CurrentFile = Path.GetFileNameWithoutExtension(file);
         }
async void Atreyu.ViewModels.CombinedHeatmapViewModel.SumFrames (FrameRange sumFrames)
The sum frames.
Parameters
sumFrames The frame range to sum.
Definition at line 533 of file CombinedHeatmapViewModel.cs.
         {
             if (sumFrames == null)
             {
                 return;
             }
             if (this.UimfData == null)
             {
                 return;
             }
             this.currentStartFrame = sumFrames.StartFrame < 1 ? 1 : sumFrames.StartFrame;
             this.currentEndFrame = sumFrames.EndFrame < 1 ? 1 : sumFrames.EndFrame;
             await
                 this.UimfData.ReadData(
                     this.UimfData.CurrentMinBin,
                     this.UimfData.CurrentMaxBin,
                     this.currentStartFrame,
                     this.currentEndFrame,
                     this.Height,
                     this.Width,
                     this.UimfData.StartScan,
                     this.UimfData.EndScan,
                     ReturnGatedData);
         }
void Atreyu.ViewModels.CombinedHeatmapViewModel.UpdateLowGate (double gate)
The update low gate.
Parameters
gate The gate.
Definition at line 568 of file CombinedHeatmapViewModel.cs.
         {
             if (this.UimfData == null)
             {
                 return;
             }
             this.UimfData.UpdateLowGate(gate);
         }
async Task Atreyu.ViewModels.CombinedHeatmapViewModel.UpdateMzWindow () private
Updates the mz window.
Returns
The Task.
Definition at line 605 of file CombinedHeatmapViewModel.cs.
         {
             this.mzWindow = this.uimfData.GetBinRangeForMzWindow(this.MzCenter, this.PartsPerMillion);
             this.HeatMapViewModel.MzWindow = this.mzWindow;
             this.UimfData.RangeUpdateList.Enqueue(this.mzWindow);
             await this.UimfData.CheckQueue();
         }
async Task Atreyu.ViewModels.CombinedHeatmapViewModel.ZoomOut ()
The zoom out.
Returns
The Task.
Definition at line 584 of file CombinedHeatmapViewModel.cs.
References Atreyu.Models.UimfData.MaxBins, and Atreyu.Models.UimfData.Scans.
         {
             var scanRange = new ScanRange(0, this.UimfData.Scans);
             var binRange = this.windowMz ? this.mzWindow : new BinRange(0, this.UimfData.MaxBins);
             this.UimfData.RangeUpdateList.Enqueue(scanRange);
             this.UimfData.RangeUpdateList.Enqueue(binRange);
             await this.UimfData.CheckQueue();
         }
Member Data Documentation
double Atreyu.ViewModels.CombinedHeatmapViewModel.centerMz = 1000.0D private
The center of the m/z window.
Definition at line 63 of file CombinedHeatmapViewModel.cs.
bool Atreyu.ViewModels.CombinedHeatmapViewModel.circularWaitIsVisible private
A private backing field for a property that indicates whether The circular wait is visible.
Definition at line 68 of file CombinedHeatmapViewModel.cs.
int Atreyu.ViewModels.CombinedHeatmapViewModel.currentEndFrame private
The current end frame.
Definition at line 73 of file CombinedHeatmapViewModel.cs.
string Atreyu.ViewModels.CombinedHeatmapViewModel.currentFile = "Heatmap" private
The name of the current file that is loaded, without path or extension.
Definition at line 78 of file CombinedHeatmapViewModel.cs.
int Atreyu.ViewModels.CombinedHeatmapViewModel.currentStartFrame private
The current start frame.
Definition at line 83 of file CombinedHeatmapViewModel.cs.
int Atreyu.ViewModels.CombinedHeatmapViewModel.height private
The height of the view.
Definition at line 88 of file CombinedHeatmapViewModel.cs.
BinRange Atreyu.ViewModels.CombinedHeatmapViewModel.mzWindow = new BinRange() private
The m/z window represented as a BinRange.
Definition at line 93 of file CombinedHeatmapViewModel.cs.
double Atreyu.ViewModels.CombinedHeatmapViewModel.partsPerMillion = 150.0D private
The parts per million tolerance for the m/z window.
Definition at line 98 of file CombinedHeatmapViewModel.cs.
const bool Atreyu.ViewModels.CombinedHeatmapViewModel.ReturnGatedData = true private
The return gated data bool.
Definition at line 54 of file CombinedHeatmapViewModel.cs.
UimfData Atreyu.ViewModels.CombinedHeatmapViewModel.uimfData private
The uimf data.
Definition at line 103 of file CombinedHeatmapViewModel.cs.
int Atreyu.ViewModels.CombinedHeatmapViewModel.width private
The width of the view.
Definition at line 108 of file CombinedHeatmapViewModel.cs.
bool Atreyu.ViewModels.CombinedHeatmapViewModel.windowMz private
Whether or not to window the M/Z.
Definition at line 113 of file CombinedHeatmapViewModel.cs.
Property Documentation
bool Atreyu.ViewModels.CombinedHeatmapViewModel.CircularWaitIsVisible get set
Gets or sets a value indicating whether the circular wait is visible.
Definition at line 262 of file CombinedHeatmapViewModel.cs.
string Atreyu.ViewModels.CombinedHeatmapViewModel.CurrentFile get set
Gets or sets the current file.
Definition at line 278 of file CombinedHeatmapViewModel.cs.
FrameManipulationViewModel Atreyu.ViewModels.CombinedHeatmapViewModel.FrameManipulationViewModel get set
Gets the frame manipulation view model.
Definition at line 293 of file CombinedHeatmapViewModel.cs.
HeatMapViewModel Atreyu.ViewModels.CombinedHeatmapViewModel.HeatMapViewModel get set
Gets the heat map view model.
Definition at line 298 of file CombinedHeatmapViewModel.cs.
int Atreyu.ViewModels.CombinedHeatmapViewModel.Height get set
Gets the height of the Heat map plot.
Definition at line 304 of file CombinedHeatmapViewModel.cs.
GateSliderViewModel Atreyu.ViewModels.CombinedHeatmapViewModel.LowValueGateSliderViewModel get set
Gets the low value gate slider view model.
Definition at line 319 of file CombinedHeatmapViewModel.cs.
double Atreyu.ViewModels.CombinedHeatmapViewModel.MzCenter get set
Gets or sets the mz center.
Definition at line 325 of file CombinedHeatmapViewModel.cs.
bool Atreyu.ViewModels.CombinedHeatmapViewModel.MzRangeEnabled get set
Gets or sets a value indicating whether mz range enabled.
Definition at line 341 of file CombinedHeatmapViewModel.cs.
MzSpectraViewModel Atreyu.ViewModels.CombinedHeatmapViewModel.MzSpectraViewModel get set
Gets the mz spectra view model.
Definition at line 356 of file CombinedHeatmapViewModel.cs.
double Atreyu.ViewModels.CombinedHeatmapViewModel.PartsPerMillion get set
Gets or sets the parts per million.
Definition at line 362 of file CombinedHeatmapViewModel.cs.
TotalIonChromatogramViewModel Atreyu.ViewModels.CombinedHeatmapViewModel.TotalIonChromatogramViewModel get set
Gets the total ion chromatogram view model.
Definition at line 377 of file CombinedHeatmapViewModel.cs.
UimfData Atreyu.ViewModels.CombinedHeatmapViewModel.UimfData get set
Gets or sets the data relevant to the UIMF that is loaded.
Definition at line 383 of file CombinedHeatmapViewModel.cs.
int Atreyu.ViewModels.CombinedHeatmapViewModel.Width get set
Gets the width of the Heat map plot.
Definition at line 399 of file CombinedHeatmapViewModel.cs.
ReactiveCommand<object> Atreyu.ViewModels.CombinedHeatmapViewModel.ZoomOutFull get set
Gets the zoom out full.
Definition at line 414 of file CombinedHeatmapViewModel.cs.
The documentation for this class was generated from the following file:
Falkor/Atreyu/Atreyu/ViewModels/CombinedHeatmapViewModel.cs