Atreyu: Atreyu.ViewModels.TotalIonChromatogramViewModel Class Reference
Atreyu.ViewModels.TotalIonChromatogramViewModel Class Reference
The total ion chromatogram view model.
Public Member Functions
TotalIonChromatogramViewModel ()
Initializes a new instance of the TotalIonChromatogramViewModel class.
void ChangeEndScan (int value)
The change end scan.
void ChangeStartScan (int value)
The change start scan.
IDictionary< int, double > GetTicData ()
The get tic data.
Image GetTicImage ()
Gets the image of the tic plot.
void UpdateFrameData (double[,] data)
The update frame data.
void UpdateReference (UimfData uimfDataNew)
The update reference.
Properties
PlotModel TicPlotModel [get, set]
Gets or sets the tic plot model.
Private Member Functions
void FindPeaks ()
Find the peaks in the current data set and adds an annotation point with the resolution to the TIC.
Private Attributes
int endScan
The end scan.
double[,] frameData
The frame data.
Dictionary< int, double > frameDictionary
The frame data.
int startScan
The start scan.
PlotModel ticPlotModel
The tic plot model.
UimfData uimfData
The uimf data.
Detailed Description
The total ion chromatogram view model.
Definition at line 55 of file TotalIonChromatogramViewModel.cs.
Constructor & Destructor Documentation
Atreyu.ViewModels.TotalIonChromatogramViewModel.TotalIonChromatogramViewModel ()
Initializes a new instance of the TotalIonChromatogramViewModel class.
Definition at line 97 of file TotalIonChromatogramViewModel.cs.
         {
         }
Member Function Documentation
void Atreyu.ViewModels.TotalIonChromatogramViewModel.ChangeEndScan (int value)
The change end scan.
Parameters
value The value.
Definition at line 131 of file TotalIonChromatogramViewModel.cs.
Referenced by Atreyu.ViewModels.CombinedHeatmapViewModel.CombinedHeatmapViewModel().
         {
             this.endScan = value;
         }
void Atreyu.ViewModels.TotalIonChromatogramViewModel.ChangeStartScan (int value)
The change start scan.
Parameters
value The value.
Definition at line 142 of file TotalIonChromatogramViewModel.cs.
Referenced by Atreyu.ViewModels.CombinedHeatmapViewModel.CombinedHeatmapViewModel().
         {
             this.startScan = value;
         }
void Atreyu.ViewModels.TotalIonChromatogramViewModel.FindPeaks () private
Find the peaks in the current data set and adds an annotation point with the resolution to the TIC.
Definition at line 294 of file TotalIonChromatogramViewModel.cs.
         {
             this.ticPlotModel.Annotations.Clear();
             // Create a new dictionary so we don't modify the original one
             var tempFrameDict = new Dictionary<double, double>(this.uimfData.Scans);
             for (var i = 0; i < this.uimfData.Scans; i++)
             {
                 // this is a hack to make the library work and return the proper location index
                 double junk;
                 tempFrameDict.Add(i, this.frameDictionary.TryGetValue(i, out junk) ? junk : 0);
             }
             var results = Utilities.PeakFinder.FindPeaks(tempFrameDict.ToList());
             foreach (var peakInformation in results.Peaks)
             {
                 var resolutionString = peakInformation.ResolvingPower.ToString("F1", CultureInfo.InvariantCulture);
                 var peakPoint = new OxyPlot.Annotations.PointAnnotation
{
                                         Text = "R=" + resolutionString,
                                         X = peakInformation.PeakCenter,
                                         Y = peakInformation.Intensity / 2.5,
                                         ToolTip = peakInformation.ToString()
                                     };
                 this.ticPlotModel.Annotations.Add(peakPoint);
             }
         }
IDictionary<int, double> Atreyu.ViewModels.TotalIonChromatogramViewModel.GetTicData ()
The get tic data.
Returns
The dictionary of tic data, keyed by scan.
Definition at line 153 of file TotalIonChromatogramViewModel.cs.
         {
             return this.frameDictionary;
         }
Image Atreyu.ViewModels.TotalIonChromatogramViewModel.GetTicImage ()
Gets the image of the tic plot.
Returns
The Image.
Definition at line 164 of file TotalIonChromatogramViewModel.cs.
         {
             var stream = new MemoryStream();
             PngExporter.Export(
                 this.TicPlotModel,
                 stream,
                 (int)this.TicPlotModel.Width,
                 (int)this.TicPlotModel.Height,
                 OxyColors.White);
             Image image = new Bitmap(stream);
             return image;
         }
void Atreyu.ViewModels.TotalIonChromatogramViewModel.UpdateFrameData (double data[,])
The update frame data.
Parameters
data The Data.
Definition at line 184 of file TotalIonChromatogramViewModel.cs.
Referenced by Atreyu.ViewModels.CombinedHeatmapViewModel.CombinedHeatmapViewModel().
         {
             if (data == null)
             {
                 return;
             }
             this.frameData = data;
             if (this.endScan == 0)
             {
                 this.startScan = 0;
                 this.endScan = 359;
             }
             this.frameDictionary = new Dictionary<int, double>();
             for (var i = 0; i < this.frameData.GetLength(0); i++)
             {
                 var index = i + this.startScan;
                 for (var j = 0; j < this.frameData.GetLength(1); j++)
                 {
                     if (this.frameDictionary.ContainsKey(index))
                     {
                         this.frameDictionary[index] += this.frameData[i, j];
                     }
                     else
                     {
                         this.frameDictionary.Add(index, this.frameData[i, j]);
                     }
                 }
             }
             var series = this.TicPlotModel.Series[0] as LineSeries;
             if (series == null)
             {
                 return;
             }
             series.MarkerType = MarkerType.Circle;
             series.MarkerSize = 2.5;
             // series.MarkerStrokeThickness = 2;
             series.MarkerFill = OxyColors.Black;
             series.BrokenLineColor = OxyColors.Automatic;
             series.BrokenLineStyle = LineStyle.Dot;
             series.BrokenLineThickness = 1;
             series.Points.Clear();
             foreach (var d in this.frameDictionary)
             {
                 series.Points.Add(new DataPoint(d.Key, d.Value));
                 series.Points.Add(new DataPoint(double.NaN, double.NaN));
             }
             this.FindPeaks();
             this.TicPlotModel.InvalidatePlot(true);
         }
void Atreyu.ViewModels.TotalIonChromatogramViewModel.UpdateReference (UimfData uimfDataNew)
The update reference.
Parameters
uimfDataNew The new UimfData that is coming in.
Definition at line 250 of file TotalIonChromatogramViewModel.cs.
Referenced by Atreyu.ViewModels.CombinedHeatmapViewModel.CombinedHeatmapViewModel().
         {
             this.uimfData = uimfDataNew;
             if (this.TicPlotModel != null)
             {
                 return;
             }
             this.TicPlotModel = new PlotModel();
             var linearAxis = new LinearAxis
{
                                      Position = AxisPosition.Top,
                                      AbsoluteMinimum = 0,
                                      IsPanEnabled = false,
                                      IsZoomEnabled = false,
                                      Title = "Scan",
                                      MinorTickSize = 0
                                  };
             this.TicPlotModel.Axes.Add(linearAxis);
             var linearYAxis = new LinearAxis
{
                                       IsZoomEnabled = false,
                                       AbsoluteMinimum = 0,
                                       MinimumPadding = 0.1,
                                       MaximumPadding = 0.1,
                                       IsPanEnabled = false,
                                       IsAxisVisible = false,
                                       Title = "Intensity"
                                   };
             this.TicPlotModel.Axes.Add(linearYAxis);
             var series = new LineSeries { Color = OxyColors.Black, };
             this.TicPlotModel.Series.Add(series);
         }
Member Data Documentation
int Atreyu.ViewModels.TotalIonChromatogramViewModel.endScan private
The end scan.
Definition at line 62 of file TotalIonChromatogramViewModel.cs.
double [,] Atreyu.ViewModels.TotalIonChromatogramViewModel.frameData private
The frame data.
Definition at line 67 of file TotalIonChromatogramViewModel.cs.
Dictionary<int, double> Atreyu.ViewModels.TotalIonChromatogramViewModel.frameDictionary private
The frame data.
Definition at line 72 of file TotalIonChromatogramViewModel.cs.
int Atreyu.ViewModels.TotalIonChromatogramViewModel.startScan private
The start scan.
Definition at line 77 of file TotalIonChromatogramViewModel.cs.
PlotModel Atreyu.ViewModels.TotalIonChromatogramViewModel.ticPlotModel private
The tic plot model.
Definition at line 82 of file TotalIonChromatogramViewModel.cs.
UimfData Atreyu.ViewModels.TotalIonChromatogramViewModel.uimfData private
The uimf data.
Definition at line 87 of file TotalIonChromatogramViewModel.cs.
Property Documentation
PlotModel Atreyu.ViewModels.TotalIonChromatogramViewModel.TicPlotModel get set
Gets or sets the tic plot model.
Definition at line 109 of file TotalIonChromatogramViewModel.cs.
The documentation for this class was generated from the following file:
Falkor/Atreyu/Atreyu/ViewModels/TotalIonChromatogramViewModel.cs