Atreyu: UimfDataExtractor.DataExporter Class Reference
UimfDataExtractor.DataExporter Class Reference
The data exporter class.
Static Public Member Functions
static FileInfo GetOutputLocation (FileInfo originFile, string dataType, int frameNumber, string fileExtension="csv")
Gets output location, based on the name and location of the origin file, the type of data, and the current frame.
static void OutputBulkMzPeakData (string dateString, string inputFolder, IEnumerable< BulkPeakData > mzPeaks)
The output bulk mz peak data method.
static void OutputBulkTicPeakData (string dateString, string inputFolder, IEnumerable< BulkPeakData > ticPeaks)
The output bulk tic peak data.
static void OutputBulkXicPeakData (string dateString, string inputFolder, IEnumerable< BulkPeakData > xicPeaks, double mz, double tolerance)
The output bulk xic peak data.
static void OutputHeatMap (double[,] data, FileInfo outputFile, bool verbose)
Handles writing the heat map to file.
static void OutputMz (IEnumerable< KeyValuePair< double, int >> mzKeyedIntensities, FileInfo outputFile, bool verbose)
Handles writing the mass over charge information to file.
static void OutputPeaks (PeakSet peakSet, FileInfo outputFile)
The output peaks.
static void OutputTiCbyTime (IEnumerable< ScanInfo > timeKeyedIntensities, FileInfo outputFile, bool verbose)
Handles Outputting the Total Ion Chromatogram data to file.
static void OutputXiCbyTime (IEnumerable< KeyValuePair< double, double >> data, FileInfo outputFile, bool verbose)
The output xic by time.
Properties
static DirectoryInfo InputDirectory [get, set]
Gets or sets the input directory.
static DirectoryInfo OutputDirectory [get, set]
Gets or sets the output directory.
Static Private Member Functions
static StreamWriter GetFileStream (FileInfo outputFile)
Makes sure that the output directory exists, checks to see if the file exists (and deletes it if it does) then creates an output stream for writing text files.
static XmlWriter GetXmlWriter (FileInfo file)
The get xml writer.
static void PrintFileCreationError (string filename)
Print a file creation error.
Static Private Attributes
static DirectoryInfo inputDirectory
The input directory.
static DirectoryInfo outputDirectory
The output directory.
Detailed Description
The data exporter class.
Definition at line 46 of file DataExporter.cs.
Member Function Documentation
static StreamWriter UimfDataExtractor.DataExporter.GetFileStream (FileInfo outputFile) static private
Makes sure that the output directory exists, checks to see if the file exists (and deletes it if it does) then creates an output stream for writing text files.
Parameters
outputFile The output file we want to create a text writer for.
Returns
The StreamWriter.
Definition at line 441 of file DataExporter.cs.
Referenced by UimfDataExtractor.DataExporter.GetXmlWriter(), UimfDataExtractor.DataExporter.OutputBulkMzPeakData(), UimfDataExtractor.DataExporter.OutputBulkTicPeakData(), UimfDataExtractor.DataExporter.OutputBulkXicPeakData(), UimfDataExtractor.DataExporter.OutputHeatMap(), UimfDataExtractor.DataExporter.OutputMz(), UimfDataExtractor.DataExporter.OutputTiCbyTime(), and UimfDataExtractor.DataExporter.OutputXiCbyTime().
         {
             var outstring = outputFile.DirectoryName;
             if (outstring == null)
             {
                 Console.WriteLine();
                 Console.Error.WriteLine(
                     "ERROR: We will expand upon this later, but we couldn't find the directory of the output file and it will not be output");
                 Console.WriteLine();
                 return null;
             }
             var outDirectory = new DirectoryInfo(outstring);
             if (!outDirectory.Exists)
             {
                 outDirectory.Create();
             }
             if (outputFile.Exists)
             {
                 Console.WriteLine();
                 Console.WriteLine(
                     "One of the output files (" + outputFile.FullName
                     + ") already exists, so we are deleting it Mwahahaha!");
                 Console.WriteLine();
                 outputFile.Delete();
             }
             return outputFile.CreateText();
         }
static FileInfo UimfDataExtractor.DataExporter.GetOutputLocation (FileInfo originFile, string dataType, int frameNumber, string fileExtension = "csv") static
Gets output location, based on the name and location of the origin file, the type of data, and the current frame.
Parameters
originFile The origin file, which we use for the first part of the name.
dataType The data type which is put between underscores after the name, but before the frame number.
frameNumber The frame number, if it is negative, no frame number will be printed
fileExtension an optional parameter to specify the extension of the new filename, defaults to csv
Returns
The FileInfo.
Definition at line 118 of file DataExporter.cs.
         {
             var locationRelativeToInput = originFile.FullName.Substring(inputDirectory.FullName.Length + 1);
             var nestedLocation = Path.Combine(outputDirectory.FullName, locationRelativeToInput);
             var csvFullPath = Path.ChangeExtension(nestedLocation, fileExtension);
             var oldName = new FileInfo(csvFullPath);
             var oldDir = oldName.DirectoryName;
             var newName = Path.GetFileNameWithoutExtension(csvFullPath);
             newName += "_" + dataType;
             if (frameNumber >= 0)
             {
                 newName += "_" + frameNumber.ToString("0000");
             }
             newName += Path.GetExtension(oldName.FullName);
             return oldDir == null ? null : new FileInfo(Path.Combine(oldDir, newName));
         }
static XmlWriter UimfDataExtractor.DataExporter.GetXmlWriter (FileInfo file) static private
The get xml writer.
Parameters
file The file.
Returns
The XmlWriter.
Definition at line 482 of file DataExporter.cs.
References UimfDataExtractor.DataExporter.GetFileStream().
Referenced by UimfDataExtractor.DataExporter.OutputPeaks().
         {
             return new XmlTextWriter(GetFileStream(file));
         }
static void UimfDataExtractor.DataExporter.OutputBulkMzPeakData (string dateString, string inputFolder, IEnumerable< BulkPeakData > mzPeaks) static
The output bulk mz peak data method.
Parameters
dateString The date string.
inputFolder The input folder.
mzPeaks The mz peaks.
Definition at line 156 of file DataExporter.cs.
References UimfDataExtractor.DataExporter.GetFileStream().
         {
             var filename = dateString + "_" + inputFolder + "_" + "mz" + "_" + "BulkPeakComparison.csv";
             var fullLocation = Path.Combine(outputDirectory.FullName, filename);
             var file = new FileInfo(fullLocation);
             using (var writer = GetFileStream(file))
             {
                 writer.WriteLine("File,Frame,Location,Full Width Half Max,Resolving Power");
                 foreach (var bulkPeakData in mzPeaks)
                 {
                     var temp = bulkPeakData.FileName + ",";
                     temp += bulkPeakData.FrameNumber + ",";
                     temp += bulkPeakData.Location + ",";
                     temp += bulkPeakData.FullWidthHalfMax + ",";
                     temp += bulkPeakData.ResolvingPower;
                     writer.WriteLine(temp);
                 }
             }
         }
static void UimfDataExtractor.DataExporter.OutputBulkTicPeakData (string dateString, string inputFolder, IEnumerable< BulkPeakData > ticPeaks) static
The output bulk tic peak data.
Parameters
dateString The date string.
inputFolder The input folder.
ticPeaks The tic peaks.
Definition at line 191 of file DataExporter.cs.
References UimfDataExtractor.DataExporter.GetFileStream().
         {
             var filename = dateString + "_" + inputFolder + "_" + "tic" + "_" + "BulkPeakComparison.csv";
             var fullLocation = Path.Combine(outputDirectory.FullName, filename);
             var file = new FileInfo(fullLocation);
             using (var writer = GetFileStream(file))
             {
                 writer.WriteLine("File,Frame,Location,Full Width Half Max,Resolving Power");
                 foreach (var bulkPeakData in ticPeaks)
                 {
                     var temp = bulkPeakData.FileName + ",";
                     temp += bulkPeakData.FrameNumber + ",";
                     temp += bulkPeakData.Location + ",";
                     temp += bulkPeakData.FullWidthHalfMax + ",";
                     temp += bulkPeakData.ResolvingPower;
                     writer.WriteLine(temp);
                 }
             }
         }
static void UimfDataExtractor.DataExporter.OutputBulkXicPeakData (string dateString, string inputFolder, IEnumerable< BulkPeakData > xicPeaks, double mz, double tolerance) static
The output bulk xic peak data.
Parameters
dateString The date string.
inputFolder The input folder.
xicPeaks The xic peaks.
mz The mz.
tolerance The tolerance.
Definition at line 232 of file DataExporter.cs.
References UimfDataExtractor.DataExporter.GetFileStream().
         {
             var filename = dateString + "_" + inputFolder + "_" + "XiC_mz_" + mz + "_tolerance_" + tolerance
                            + "BulkPeakComparison.csv";
             var fullLocation = Path.Combine(outputDirectory.FullName, filename);
             var file = new FileInfo(fullLocation);
             using (var writer = GetFileStream(file))
             {
                 writer.WriteLine("File,Frame,Drift Time,Full Width Half Max,Resolving Power");
                 foreach (var bulkPeakData in xicPeaks)
                 {
                     var temp = bulkPeakData.FileName + ",";
                     temp += bulkPeakData.FrameNumber + ",";
                     temp += bulkPeakData.Location + ",";
                     temp += bulkPeakData.FullWidthHalfMax + ",";
                     temp += bulkPeakData.ResolvingPower;
                     writer.WriteLine(temp);
                 }
             }
         }
static void UimfDataExtractor.DataExporter.OutputHeatMap (double data[,], FileInfo outputFile, bool verbose) static
Handles writing the heat map to file.
Parameters
data The data to be written.
outputFile The output file.
verbose The verbose.
Definition at line 270 of file DataExporter.cs.
References UimfDataExtractor.DataExporter.GetFileStream(), and UimfDataExtractor.DataExporter.PrintFileCreationError().
         {
             using (var stream = GetFileStream(outputFile))
             {
                 if (stream == null)
                 {
                     PrintFileCreationError(outputFile.FullName);
                     return;
                 }
                 for (var bin = 0; bin < data.GetLength(1); bin++)
                 {
                     var content = string.Empty;
                     for (var scan = 0; scan < data.GetLength(0); scan++)
                     {
                         content += data[scan, bin].ToString("0.00") + ",";
                     }
                     stream.WriteLine(content);
                 }
                 if (verbose)
                 {
                     Console.WriteLine("flushing data to file " + outputFile.FullName);
                 }
             }
         }
static void UimfDataExtractor.DataExporter.OutputMz (IEnumerable< KeyValuePair< double, int >> mzKeyedIntensities, FileInfo outputFile, bool verbose) static
Handles writing the mass over charge information to file.
Parameters
mzKeyedIntensities The Mass over charge keyed intensities.
outputFile The output file.
verbose The verbose.
Definition at line 310 of file DataExporter.cs.
References UimfDataExtractor.DataExporter.GetFileStream(), and UimfDataExtractor.DataExporter.PrintFileCreationError().
         {
             using (var stream = GetFileStream(outputFile))
             {
                 if (stream == null)
                 {
                     PrintFileCreationError(outputFile.FullName);
                     return;
                 }
                 foreach (var kvp in mzKeyedIntensities)
                 {
                     stream.WriteLine(kvp.Key + ", " + kvp.Value);
                 }
                 if (verbose)
                 {
                     Console.WriteLine("flushing data to file " + outputFile.FullName);
                 }
             }
         }
static void UimfDataExtractor.DataExporter.OutputPeaks (PeakSet peakSet, FileInfo outputFile) static
The output peaks.
Parameters
peakSet The peak set.
outputFile The output file.
Definition at line 344 of file DataExporter.cs.
References UimfDataExtractor.DataExporter.GetXmlWriter().
         {
             var serializer = new DataContractSerializer(typeof(PeakSet));
             using (var writer = GetXmlWriter(outputFile))
             {
                 serializer.WriteObject(writer, peakSet);
             }
         }
static void UimfDataExtractor.DataExporter.OutputTiCbyTime (IEnumerable< ScanInfo > timeKeyedIntensities, FileInfo outputFile, bool verbose) static
Handles Outputting the Total Ion Chromatogram data to file.
Parameters
timeKeyedIntensities The time keyed intensities.
outputFile The output file.
verbose The verbose.
Definition at line 365 of file DataExporter.cs.
References UimfDataExtractor.DataExporter.GetFileStream(), and UimfDataExtractor.DataExporter.PrintFileCreationError().
         {
             using (var stream = GetFileStream(outputFile))
             {
                 if (stream == null)
                 {
                     PrintFileCreationError(outputFile.FullName);
                     return;
                 }
                 foreach (var timeKeyedIntensity in timeKeyedIntensities)
                 {
                     stream.WriteLine(timeKeyedIntensity.DriftTime + ", " + timeKeyedIntensity.TIC);
                 }
                 if (verbose)
                 {
                     Console.WriteLine("flushing data to file " + outputFile.FullName);
                 }
             }
         }
static void UimfDataExtractor.DataExporter.OutputXiCbyTime (IEnumerable< KeyValuePair< double, double >> data, FileInfo outputFile, bool verbose) static
The output xic by time.
Parameters
data The data.
outputFile The output file.
verbose The verbose.
Definition at line 402 of file DataExporter.cs.
References UimfDataExtractor.DataExporter.GetFileStream(), and UimfDataExtractor.DataExporter.PrintFileCreationError().
         {
             using (var stream = GetFileStream(outputFile))
             {
                 if (stream == null)
                 {
                     PrintFileCreationError(outputFile.FullName);
                     return;
                 }
                 foreach (var kvp in data)
                 {
                     stream.WriteLine(kvp.Key + ", " + kvp.Value);
                 }
                 if (verbose)
                 {
                     Console.WriteLine("flushing data to file " + outputFile.FullName);
                 }
             }
         }
static void UimfDataExtractor.DataExporter.PrintFileCreationError (string filename) static private
Print a file creation error.
Parameters
filename The filename.
Definition at line 493 of file DataExporter.cs.
Referenced by UimfDataExtractor.DataExporter.OutputHeatMap(), UimfDataExtractor.DataExporter.OutputMz(), UimfDataExtractor.DataExporter.OutputTiCbyTime(), and UimfDataExtractor.DataExporter.OutputXiCbyTime().
         {
             Console.WriteLine();
             Console.Error.WriteLine(
                 "We were unable to create" + filename
                 + "so we aren't outputting data to it either, we are petty like that");
             Console.WriteLine();
         }
Member Data Documentation
DirectoryInfo UimfDataExtractor.DataExporter.inputDirectory static private
The input directory.
Definition at line 53 of file DataExporter.cs.
DirectoryInfo UimfDataExtractor.DataExporter.outputDirectory static private
The output directory.
Definition at line 58 of file DataExporter.cs.
Property Documentation
DirectoryInfo UimfDataExtractor.DataExporter.InputDirectory static get set
Gets or sets the input directory.
Definition at line 68 of file DataExporter.cs.
Referenced by UimfDataExtractor.UimfProcessor.ExtractData().
DirectoryInfo UimfDataExtractor.DataExporter.OutputDirectory static get set
Gets or sets the output directory.
Definition at line 84 of file DataExporter.cs.
The documentation for this class was generated from the following file:
Falkor/Atreyu/UIMF Data Extractor/DataExporter.cs