Atreyu: Atreyu.ViewModels.MzSpectraViewModel Class Reference
Atreyu.ViewModels.MzSpectraViewModel Class Reference
The view model for properly displaying the mz spectra graph.
Classes
class KvpCompare< TValue >
A private class that specifies how to compare a Key Value Pair class where the key is an integer.
struct ResolutionDatapoint
The resolution data point.
Public Member Functions
MzSpectraViewModel ()
Initializes a new instance of the MzSpectraViewModel class.
void ChangeEndBin (int bin)
Changes the end bin for proper graph display.
void ChangeStartBin (int bin)
Changes the start bin for proper graph display.
void CreatePlotModel ()
Creates or recreates the create plot model.
IDictionary< double, double > GetMzDataCompressed ()
Gets a dictionary of the m/z data that has been compressed.
Image GetMzImage ()
Get the current image of the m/z graph.
void UpdateFrameData (double[,] framedata)
Update frame data.
void UpdateReference (UimfData uimfDataNew)
Updates the reference to UIMF data.
Properties
double[] BinToMzMap [get, set]
Gets or sets the bin to mz map.
MzCalibrator Calibrator [get, set]
Gets or sets the mz calibrator.
double Intercept [get, set]
Gets or sets the intercept.
double[] MzArray [get, set]
Gets or sets the mz array.
int[] MzIntensities [get, set]
Gets or sets the mz intensities.
PlotModel MzPlotModel [get, set]
Gets or sets the mz plot model.
bool ShowMz [get, set]
Gets or sets a value indicating whether show mz.
double Slope [get, set]
Gets or sets the slope.
double ValuesPerPixelY [get, set]
Gets or sets the values per pixel y.
Private Member Functions
void FindPeaks ()
Find the peaks in the current data set and adds an annotation point with the resolution to the m/z.
Private Attributes
int endMzBin
The end mz bin.
double[,] frameData
The raw frame data that is compressed on the Y axis.
Dictionary< double, double > frameDictionary
The bin centric frame data that has been compressed.
double intercept
The calibration intercept.
Dictionary< double, double > mzFrameData
The mz frame data that has been compressed.
PlotModel mzPlotModel
The plot model for the mz.
bool showMz
Specifies whether or not to show the mz.
double slope
The calibration slope.
int startMzBin
The start mz bin.
UimfData uimfData
The uimf data reference.
Detailed Description
The view model for properly displaying the mz spectra graph.
Definition at line 38 of file MzSpectraViewModel.cs.
Constructor & Destructor Documentation
Atreyu.ViewModels.MzSpectraViewModel.MzSpectraViewModel ()
Initializes a new instance of the MzSpectraViewModel class.
Definition at line 100 of file MzSpectraViewModel.cs.
         {
             this.WhenAnyValue(vm => vm.ShowMz).Subscribe(b => this.UpdateFrameData(this.frameData));
         }
Member Function Documentation
void Atreyu.ViewModels.MzSpectraViewModel.ChangeEndBin (int bin)
Changes the end bin for proper graph display.
Parameters
bin The bin to change to.
Definition at line 208 of file MzSpectraViewModel.cs.
Referenced by Atreyu.ViewModels.CombinedHeatmapViewModel.CombinedHeatmapViewModel().
         {
             this.endMzBin = bin;
         }
void Atreyu.ViewModels.MzSpectraViewModel.ChangeStartBin (int bin)
Changes the start bin for proper graph display.
Parameters
bin The bin to change to.
Definition at line 219 of file MzSpectraViewModel.cs.
Referenced by Atreyu.ViewModels.CombinedHeatmapViewModel.CombinedHeatmapViewModel().
         {
             this.startMzBin = bin;
         }
void Atreyu.ViewModels.MzSpectraViewModel.CreatePlotModel ()
Creates or recreates the create plot model.
Definition at line 227 of file MzSpectraViewModel.cs.
         {
             this.MzPlotModel = new PlotModel();
             var linearAxis = new LinearAxis
{
                                      Position = AxisPosition.Right,
                                      AbsoluteMinimum = 0,
                                      Key = "XAxisKey",
                                      IsPanEnabled = false,
                                      IsZoomEnabled = false,
                                      MinimumPadding = 0.0,
                                      Title = this.ShowMz ? "m/z" : "Bin",
                                      StringFormat = "f2"
                                  };
             this.MzPlotModel.Axes.Add(linearAxis);
             var linearYAxis = new LinearAxis
{
                                       AbsoluteMinimum = 0,
                                       IsZoomEnabled = false,
                                       Position = AxisPosition.Top,
                                       Key = "YAxisKey",
                                       IsPanEnabled = false,
                                       MinimumPadding = 0,
                                       StartPosition = 1,
                                       EndPosition = 0,
                                   };
             this.MzPlotModel.Axes.Add(linearYAxis);
             var series = new LineSeries
{
                                  Color = OxyColors.Black,
                                  YAxisKey = linearAxis.Key,
                                  XAxisKey = linearYAxis.Key,
                                  StrokeThickness = 1
                              };
             this.MzPlotModel.Series.Add(series);
         }
void Atreyu.ViewModels.MzSpectraViewModel.FindPeaks () private
Find the peaks in the current data set and adds an annotation point with the resolution to the m/z.
Definition at line 405 of file MzSpectraViewModel.cs.
         {
             var datapointList = new List<ResolutionDatapoint>();
             const int Precision = 10000;
             this.mzPlotModel.Annotations.Clear();
             if (!this.ShowMz)
             {
                 // This currently does not support peakfinding in bin mode due to potential headaches,
                 // But as it seems users never use that mode, it is a non-issue for now.
                 return;
             }
             var peakDetector = new PeakDetector();
             var finderOptions = PeakDetector.GetDefaultSICPeakFinderOptions();
             List<double> smoothedY;
             // Create a new dictionary so we don't modify the original one
             var tempFrameList = new List<KeyValuePair<int, double>>(this.uimfData.MaxBins);
             // We have to give it integers, but we need the mz, so we will multiply the mz by the precision
             // and later get the correct value back by dividing it out again
             for (var i = 0; i < this.MzArray.Length && i < this.MzIntensities.Length; i++)
             {
                 tempFrameList.Add(
                     new KeyValuePair<int, double>((int)(this.MzArray[i] * Precision), this.MzIntensities[i]));
             }
             // I am not sure what this does and need to talk to Matt Monroe, but in the example exe file that came with the library
             // they used half of the length of the list in their previous examples and this seems to work on teh zoomed out version
             // but not when we zoom in, it seems like an offset problem.
             var originalpeakLocation = tempFrameList.Count / 2;
             var allPeaks = peakDetector.FindPeaks(
                 finderOptions,
                 tempFrameList.OrderBy(x => x.Key).ToList(),
                 originalpeakLocation,
                 out smoothedY);
             var topThreePeaks = allPeaks.OrderByDescending(peak => smoothedY[peak.LocationIndex]).Take(3);
             foreach (var peak in topThreePeaks)
             {
                 const double Tolerance = 0.01;
                 var centerPoint = tempFrameList.ElementAt(peak.LocationIndex);
                 var offsetMz = centerPoint.Key; // + firstpoint.Key;
                 var intensity = centerPoint.Value;
                 var smoothedPeakIntensity = smoothedY[peak.LocationIndex];
                 var realMz = (double)offsetMz / Precision;
                 var halfmax = smoothedPeakIntensity / 2.0;
                 var currPoint = new KeyValuePair<int, double>(0, 0);
                 var currPointIndex = 0;
                 double leftMidpoint = 0;
                 double rightMidPoint = 0;
                 var leftSidePeaks = new List<KeyValuePair<int, double>>();
                 for (var l = peak.LeftEdge; l < peak.LocationIndex && l < tempFrameList.Count; l++)
                 {
                     leftSidePeaks.Add(tempFrameList[l]);
                 }
                 var rightSidePeaks = new List<KeyValuePair<int, double>>();
                 for (var r = peak.LocationIndex; r < peak.RightEdge && r < tempFrameList.Count; r++)
                 {
                     rightSidePeaks.Add(tempFrameList[r]);
                 }
                 // find the left side half max
                 foreach (var leftSidePeak in leftSidePeaks)
                 {
                     var prevPoint = currPoint;
                     currPoint = leftSidePeak;
                     var prevPointIndex = currPointIndex;
                     currPointIndex = tempFrameList.BinarySearch(currPoint, new KvpCompare<double>());
                     if (smoothedY[currPointIndex] < halfmax)
                     {
                         continue;
                     }
                     if (Math.Abs(smoothedY[currPointIndex] - halfmax) < Tolerance)
                     {
                         leftMidpoint = currPoint.Key;
                         continue;
                     }
                     double a1 = prevPoint.Key;
                     double a2 = currPoint.Key;
                     double c = halfmax;
                     double b1 = smoothedY[prevPointIndex];
                     double b2 = smoothedY[currPointIndex];
                     leftMidpoint = a1 + ((a2 - a1) * ((c - b1) / (b2 - b1)));
                     break;
                 }
                 // find the right side of the half max
                 foreach (var rightSidePeak in rightSidePeaks)
                 {
                     var prevPoint = currPoint;
                     currPoint = rightSidePeak;
                     var prevPointIndex = currPointIndex;
                     currPointIndex = tempFrameList.BinarySearch(currPoint, new KvpCompare<double>());
                     if (smoothedY[currPointIndex] > halfmax || smoothedY[currPointIndex] < 0)
                     {
                         continue;
                     }
                     if (Math.Abs(smoothedY[currPointIndex] - halfmax) < Tolerance)
                     {
                         rightMidPoint = currPoint.Key;
                         continue;
                     }
                     double a1 = prevPoint.Key;
                     double a2 = currPoint.Key;
                     double c = halfmax;
                     double b1 = smoothedY[prevPointIndex];
                     double b2 = smoothedY[currPointIndex];
                     rightMidPoint = a1 + ((a2 - a1) * ((c - b1) / (b2 - b1)));
                     break;
                 }
                 var correctedRightMidPoint = rightMidPoint / Precision;
                 var correctedLeftMidPoint = leftMidpoint / Precision;
                 var resolution = realMz / (correctedRightMidPoint - correctedLeftMidPoint);
                 var temp = new ResolutionDatapoint
{
                                    Intensity = intensity,
                                    Mz = realMz,
                                    Resolution = resolution,
                                    SmoothedIntensity = smoothedPeakIntensity
                                };
                 datapointList.Add(temp);
             }
             var tempList =
                 datapointList.Where(x => !double.IsInfinity(x.Resolution)).OrderByDescending(x => x.Intensity).Take(10);
             // Put the points on the graph
             foreach (var resolutionDatapoint in tempList)
             {
                 var resolutionString = resolutionDatapoint.Resolution.ToString("F1", CultureInfo.InvariantCulture);
                 var annotationText = "Peak Location:" + resolutionDatapoint.Mz + Environment.NewLine + "Intensity:"
                                      + resolutionDatapoint.Intensity + Environment.NewLine + "Resolution:"
                                      + resolutionString;
                 var peakPoint = new OxyPlot.Annotations.PointAnnotation
{
                                         Text = "R=" + resolutionString,
                                         X = resolutionDatapoint.Intensity / 1.03125,
                                         Y = resolutionDatapoint.Mz,
                                         ToolTip = annotationText
                                     };
                 this.mzPlotModel.Annotations.Add(peakPoint);
             }
         }
IDictionary<double, double> Atreyu.ViewModels.MzSpectraViewModel.GetMzDataCompressed ()
Gets a dictionary of the m/z data that has been compressed.
Returns
The IDictionary.
Definition at line 271 of file MzSpectraViewModel.cs.
         {
             return this.mzFrameData;
         }
Image Atreyu.ViewModels.MzSpectraViewModel.GetMzImage ()
Get the current image of the m/z graph.
Returns
The Image.
Definition at line 282 of file MzSpectraViewModel.cs.
         {
             var stream = new MemoryStream();
             PngExporter.Export(
                 this.MzPlotModel,
                 stream,
                 (int)this.MzPlotModel.Width,
                 (int)this.MzPlotModel.Height,
                 OxyColors.White);
             Image image = new Bitmap(stream);
             return image;
         }
void Atreyu.ViewModels.MzSpectraViewModel.UpdateFrameData (double framedata[,])
Update frame data.
Parameters
framedata The frame data.
Definition at line 302 of file MzSpectraViewModel.cs.
Referenced by Atreyu.ViewModels.CombinedHeatmapViewModel.CombinedHeatmapViewModel().
         {
             if (this.uimfData == null)
             {
                 return;
             }
             if (framedata == null)
             {
                 return;
             }
             if (this.BinToMzMap == null)
             {
                 return;
             }
             this.frameData = framedata;
             this.frameDictionary = new Dictionary<double, double>();
             this.mzFrameData = new Dictionary<double, double>();
             for (var j = 0; j < this.frameData.GetLength(1); j++)
             {
                 double index = j + this.startMzBin;
                 var mzIndex = this.BinToMzMap[j];
                 for (var i = 0; i < this.frameData.GetLength(0); i++)
                 {
                     if (this.frameDictionary.ContainsKey(index))
                     {
                         this.frameDictionary[index] += this.frameData[i, j];
                     }
                     else
                     {
                         this.frameDictionary.Add(index, this.frameData[i, j]);
                     }
                     if (this.mzFrameData.ContainsKey(mzIndex))
                     {
                         this.mzFrameData[mzIndex] += this.frameData[i, j];
                     }
                     else
                     {
                         this.mzFrameData.Add(mzIndex, this.frameData[i, j]);
                     }
                 }
             }
             var series = this.MzPlotModel.Series[0] as LineSeries;
             if (series != null)
             {
                 if (series.YAxis != null)
                 {
                     series.YAxis.Title = this.ShowMz ? "m/z" : "Bin";
                 }
                 series.Points.Clear();
                 if (this.ShowMz)
                 {
                     foreach (var d in this.mzFrameData)
                     {
                         series.Points.Add(new DataPoint(d.Value, d.Key));
                     }
                 }
                 else
                 {
                     foreach (var d in this.frameDictionary)
                     {
                         series.Points.Add(new DataPoint(d.Value, d.Key));
                     }
                 }
             }
             this.FindPeaks();
             this.MzPlotModel.InvalidatePlot(true);
         }
void Atreyu.ViewModels.MzSpectraViewModel.UpdateReference (UimfData uimfDataNew)
Updates the reference to UIMF data.
Parameters
uimfDataNew The uimf data that has been changed.
Definition at line 387 of file MzSpectraViewModel.cs.
Referenced by Atreyu.ViewModels.CombinedHeatmapViewModel.CombinedHeatmapViewModel().
         {
             if (uimfDataNew == null)
             {
                 return;
             }
             this.uimfData = uimfDataNew;
             this.CreatePlotModel();
         }
Member Data Documentation
int Atreyu.ViewModels.MzSpectraViewModel.endMzBin private
The end mz bin.
Definition at line 45 of file MzSpectraViewModel.cs.
double [,] Atreyu.ViewModels.MzSpectraViewModel.frameData private
The raw frame data that is compressed on the Y axis.
Definition at line 50 of file MzSpectraViewModel.cs.
Dictionary<double, double> Atreyu.ViewModels.MzSpectraViewModel.frameDictionary private
The bin centric frame data that has been compressed.
Definition at line 55 of file MzSpectraViewModel.cs.
double Atreyu.ViewModels.MzSpectraViewModel.intercept private
The calibration intercept.
Definition at line 60 of file MzSpectraViewModel.cs.
Dictionary<double, double> Atreyu.ViewModels.MzSpectraViewModel.mzFrameData private
The mz frame data that has been compressed.
Definition at line 65 of file MzSpectraViewModel.cs.
PlotModel Atreyu.ViewModels.MzSpectraViewModel.mzPlotModel private
The plot model for the mz.
Definition at line 70 of file MzSpectraViewModel.cs.
bool Atreyu.ViewModels.MzSpectraViewModel.showMz private
Specifies whether or not to show the mz.
Definition at line 75 of file MzSpectraViewModel.cs.
double Atreyu.ViewModels.MzSpectraViewModel.slope private
The calibration slope.
Definition at line 80 of file MzSpectraViewModel.cs.
int Atreyu.ViewModels.MzSpectraViewModel.startMzBin private
The start mz bin.
Definition at line 85 of file MzSpectraViewModel.cs.
UimfData Atreyu.ViewModels.MzSpectraViewModel.uimfData private
The uimf data reference.
Definition at line 90 of file MzSpectraViewModel.cs.
Property Documentation
double [] Atreyu.ViewModels.MzSpectraViewModel.BinToMzMap get set
Gets or sets the bin to mz map.
Definition at line 112 of file MzSpectraViewModel.cs.
Referenced by Atreyu.ViewModels.CombinedHeatmapViewModel.CombinedHeatmapViewModel().
MzCalibrator Atreyu.ViewModels.MzSpectraViewModel.Calibrator get set
Gets or sets the mz calibrator.
Definition at line 117 of file MzSpectraViewModel.cs.
Referenced by Atreyu.ViewModels.CombinedHeatmapViewModel.CombinedHeatmapViewModel().
double Atreyu.ViewModels.MzSpectraViewModel.Intercept get set
Gets or sets the intercept.
Definition at line 123 of file MzSpectraViewModel.cs.
double [] Atreyu.ViewModels.MzSpectraViewModel.MzArray get set
Gets or sets the mz array.
Definition at line 138 of file MzSpectraViewModel.cs.
Referenced by Atreyu.ViewModels.CombinedHeatmapViewModel.CombinedHeatmapViewModel().
int [] Atreyu.ViewModels.MzSpectraViewModel.MzIntensities get set
Gets or sets the mz intensities.
Definition at line 143 of file MzSpectraViewModel.cs.
Referenced by Atreyu.ViewModels.CombinedHeatmapViewModel.CombinedHeatmapViewModel().
PlotModel Atreyu.ViewModels.MzSpectraViewModel.MzPlotModel get set
Gets or sets the mz plot model.
Definition at line 149 of file MzSpectraViewModel.cs.
bool Atreyu.ViewModels.MzSpectraViewModel.ShowMz get set
Gets or sets a value indicating whether show mz.
Definition at line 165 of file MzSpectraViewModel.cs.
Referenced by Atreyu.ViewModels.CombinedHeatmapViewModel.CombinedHeatmapViewModel().
double Atreyu.ViewModels.MzSpectraViewModel.Slope get set
Gets or sets the slope.
Definition at line 181 of file MzSpectraViewModel.cs.
double Atreyu.ViewModels.MzSpectraViewModel.ValuesPerPixelY get set
Gets or sets the values per pixel y.
Definition at line 196 of file MzSpectraViewModel.cs.
Referenced by Atreyu.ViewModels.CombinedHeatmapViewModel.CombinedHeatmapViewModel().
The documentation for this class was generated from the following file:
Falkor/Atreyu/Atreyu/ViewModels/MzSpectraViewModel.cs