Atreyu: Utilities.PeakFinder Class Reference
Utilities.PeakFinder Class Reference
The peak finder class, gives additional information over what the magnitude peak finder provides.
Static Public Member Functions
static PeakSet FindPeaks (IReadOnlyList< KeyValuePair< double, double >> dataList, int numberOfTopPeaks=0)
Find the peaks in the data set passed and returns a list of peak information.
Static Private Member Functions
static PeakInformation CalculatePeakInformation (clsPeak peak, List< KeyValuePair< int, double >> originalList, IReadOnlyList< double > smoothedIntensityValues, int precisionUsed)
Calculates peak information.
static double FindMidPoint (List< KeyValuePair< int, double >> originalList, IReadOnlyList< double > smoothedIntensityValues, IEnumerable< KeyValuePair< int, double >> sidePoints, ref KeyValuePair< int, double > currPoint, double halfmax, double tolerance, ref int currPointIndex, Side sideToFind)
Finds the left or right half max point.
static double GetX (double yValue, double x1, double y1, double x2, double y2)
Gets an x value given a y value and two x,y points.
static List< PointInformation > ExtractPointInformation (clsPeak peak, IReadOnlyList< KeyValuePair< int, double >> originalList, IReadOnlyList< double > smoothedIntensityValues, int precisionUsed, out List< KeyValuePair< int, double >> leftSidePoints, out List< KeyValuePair< int, double >> rightSidePoints)
Gets information for points, required for calculations.
Detailed Description
The peak finder class, gives additional information over what the magnitude peak finder provides.
Definition at line 42 of file PeakFinder.cs.
Member Function Documentation
static PeakInformation Utilities.PeakFinder.CalculatePeakInformation (clsPeak peak, List< KeyValuePair< int, double >> originalList, IReadOnlyList< double > smoothedIntensityValues, int precisionUsed) static private
Calculates peak information.
Parameters
peak The peak to calculate.
originalList The original list given to the peak finder.
smoothedIntensityValues The smoothed intensity values from the peak finder.
precisionUsed The precision used when passing data to the peak finder so it can handle numbers with doubles.
Returns
The PeakInformation.
Definition at line 133 of file PeakFinder.cs.
References Utilities.PeakFinder.ExtractPointInformation(), and Utilities.PeakFinder.FindMidPoint().
Referenced by Utilities.PeakFinder.FindPeaks().
         {
             const double Tolerance = 0.01;
             var centerPoint = originalList.ElementAt(peak.LocationIndex);
             var offsetCenter = centerPoint.Key; // + firstpoint.Key;
             var intensity = centerPoint.Value;
             var smoothedPeakIntensity = smoothedIntensityValues[peak.LocationIndex];
             var realCenter = (double)offsetCenter / precisionUsed;
             var halfmax = smoothedPeakIntensity / 2.0;
             var currPoint = new KeyValuePair<int, double>(0, 0);
             var currPointIndex = 0;
             List<KeyValuePair<int, double>> leftSidePoints;
             List<KeyValuePair<int, double>> rightSidePoints;
             var allPoints = ExtractPointInformation(
                 peak,
                 originalList,
                 smoothedIntensityValues,
                 precisionUsed,
                 out leftSidePoints,
                 out rightSidePoints);
             // find the left side half max
             var leftMidpoint = FindMidPoint(
                 originalList,
                 smoothedIntensityValues,
                 leftSidePoints,
                 ref currPoint,
                 halfmax,
                 Tolerance,
                 ref currPointIndex,
                 Side.LeftSide);
             // find the right side of the half max
             var rightMidPoint = FindMidPoint(
                 originalList,
                 smoothedIntensityValues,
                 rightSidePoints,
                 ref currPoint,
                 halfmax,
                 Tolerance,
                 ref currPointIndex,
                 Side.RightSide);
             var correctedRightMidPoint = rightMidPoint / precisionUsed;
             var correctedLeftMidPoint = leftMidpoint / precisionUsed;
             var fullWidthHalfMax = correctedRightMidPoint - correctedLeftMidPoint;
             var resolution = realCenter / fullWidthHalfMax;
             var temp = new PeakInformation
{
                                AreaUnderThePeak = peak.Area,
                                FullWidthHalfMax = fullWidthHalfMax,
                                Intensity = intensity,
                                LeftMidpoint = correctedLeftMidPoint,
                                PeakCenter = realCenter,
                                RightMidpoint = correctedRightMidPoint,
                                ResolvingPower = resolution,
                                SmoothedIntensity = smoothedPeakIntensity,
                                TotalDataPointSet = allPoints
                            };
             return temp;
         }
static List<PointInformation> Utilities.PeakFinder.ExtractPointInformation (clsPeak peak, IReadOnlyList< KeyValuePair< int, double >> originalList, IReadOnlyList< double > smoothedIntensityValues, int precisionUsed, out List< KeyValuePair< int, double >> leftSidePoints, out List< KeyValuePair< int, double >> rightSidePoints) static private
Gets information for points, required for calculations.
Parameters
peak The peak found.
originalList The original list given to the peak finder.
smoothedIntensityValues The smoothed intensity values output by the peak finder.
precisionUsed The precision used.
leftSidePoints The list to store the left side points.
rightSidePoints The list to store the right side points.
Returns
The <cref>List</cref>
Definition at line 361 of file PeakFinder.cs.
Referenced by Utilities.PeakFinder.CalculatePeakInformation().
         {
             var allPoints = new List<PointInformation>();
             // build left side
             leftSidePoints = new List<KeyValuePair<int, double>>();
             for (var l = peak.LeftEdge; l < peak.LocationIndex && l < originalList.Count; l++)
             {
                 leftSidePoints.Add(originalList[l]);
                 allPoints.Add(
                     new PointInformation
{
                             Location = (double)originalList[l].Key / precisionUsed,
                             Intensity = originalList[l].Value,
                             SmoothedIntensity = smoothedIntensityValues[l]
                         });
             }
             // build right side
             rightSidePoints = new List<KeyValuePair<int, double>>();
             for (var r = peak.LocationIndex; r < peak.RightEdge && r < originalList.Count; r++)
             {
                 rightSidePoints.Add(originalList[r]);
                 allPoints.Add(
                     new PointInformation
{
                             Location = (double)originalList[r].Key / precisionUsed,
                             Intensity = originalList[r].Value,
                             SmoothedIntensity = smoothedIntensityValues[r]
                         });
             }
             return allPoints;
         }
static double Utilities.PeakFinder.FindMidPoint (List< KeyValuePair< int, double >> originalList, IReadOnlyList< double > smoothedIntensityValues, IEnumerable< KeyValuePair< int, double >> sidePoints, ref KeyValuePair< int, double > currPoint, double halfmax, double tolerance, ref int currPointIndex, Side sideToFind) static private
Finds the left or right half max point.
Parameters
originalList The original list.
smoothedIntensityValues The smoothed intensity values.
sidePoints The points making up the side you want to search for the mid point.
currPoint The current point (designed to chain together.
halfmax The half max of the peak.
tolerance The tolerance for calculation.
currPointIndex The index of the original list for the currPoint.
sideToFind The side to find.
Returns
The double.
Definition at line 233 of file PeakFinder.cs.
References Utilities.PeakFinder.GetX().
Referenced by Utilities.PeakFinder.CalculatePeakInformation().
         {
             double midpoint = 0;
             foreach (var sidePoint in sidePoints)
             {
                 var prevPoint = currPoint;
                 currPoint = sidePoint;
                 var prevPointIndex = currPointIndex;
                 currPointIndex = originalList.BinarySearch(
                     currPoint,
                     Comparer<KeyValuePair<int, double>>.Create((left, right) => left.Key - right.Key));
                 switch (sideToFind)
                 {
                     case Side.LeftSide:
                         // value is too small to be the half-max point
                         if (smoothedIntensityValues[currPointIndex] < halfmax)
{
                             continue;
                         }
                         // we got lucky and have a point at the exact half way point
                         if (Math.Abs(smoothedIntensityValues[currPointIndex] - halfmax) < tolerance)
{
                             midpoint = currPoint.Key;
                             continue;
                         }
                         break;
                     case Side.RightSide:
                         if (smoothedIntensityValues[currPointIndex] > halfmax
                             || smoothedIntensityValues[currPointIndex] < 0)
{
                             continue;
                         }
                         if (Math.Abs(smoothedIntensityValues[currPointIndex] - halfmax) < tolerance)
{
                             midpoint = currPoint.Key;
                             continue;
                         }
                         break;
                 }
                 // We didn't get luky and the two points we have are above and below where the half max would be, so we need to calculate it.
                 // Having the redundant argument names improves readability for the formula (which is broken out for future test cases
                 // ReSharper disable RedundantArgumentName
                 midpoint = GetX(
                     yValue: halfmax,
                     x1: prevPoint.Key,
                     y1: smoothedIntensityValues[prevPointIndex],
                     x2: currPoint.Key,
                     y2: smoothedIntensityValues[currPointIndex]);
                 // ReSharper restore RedundantArgumentName
                 break;
             }
             return midpoint;
         }
static PeakSet Utilities.PeakFinder.FindPeaks (IReadOnlyList< KeyValuePair< double, double >> dataList, int numberOfTopPeaks = 0) static
Find the peaks in the data set passed and returns a list of peak information.
Parameters
dataList The data List.
numberOfTopPeaks The number of peaks to return, starting with the highest intensity, if less than one it will return all peaks.
Returns
The System.Collections.Generic.List{T} of peaks.
Definition at line 58 of file PeakFinder.cs.
References Utilities.PeakFinder.CalculatePeakInformation().
         {
             const int Precision = 100000;
             var peakDetector = new PeakDetector();
             var finderOptions = PeakDetector.GetDefaultSICPeakFinderOptions();
             List<double> smoothedY;
             // Create a new dictionary so we don't modify the original one
             var tempFrameList = new List<KeyValuePair<int, double>>(dataList.Count);
             // We have to give it integers for the double, but we need this to handle doubles, so we will multiply the key by the precision
             // and later get the correct value back by dividing it out again
             // resultant linq quesry is less readable than this.
             // ReSharper disable once LoopCanBeConvertedToQuery
             // ReSharper disable once ForCanBeConvertedToForeach
             for (var i = 0; i < dataList.Count; i++)
             {
                 tempFrameList.Add(new KeyValuePair<int, double>((int)(dataList[i].Key * Precision), dataList[i].Value));
             }
             // I am not sure what the library does with this but in the example exe file that came with the library
             // they used half of the length of the list in their previous examples and this seems to work.
             // To be extra clear to future programmers, changing this number causes memory out of bounds from the peak detector
             var originalpeakLocation = tempFrameList.Count / 2;
             var allPeaks = peakDetector.FindPeaks(
                 finderOptions,
                 tempFrameList.OrderBy(x => x.Key).ToList(),
                 originalpeakLocation,
                 out smoothedY);
             IEnumerable<clsPeak> peakSet;
             // if a few peaks are wanted, it is better that we trim them up front, before we calculate the extra information
             if (numberOfTopPeaks > 0)
             {
                 var topPeaks = allPeaks.OrderByDescending(peak => smoothedY[peak.LocationIndex]).Take(numberOfTopPeaks);
                 peakSet = topPeaks;
             }
             else
             {
                 peakSet = allPeaks;
             }
             var calculatedPeakSet =
                 peakSet.Select(peak => CalculatePeakInformation(peak, tempFrameList, smoothedY, Precision))
                     .Where(p => p.ResolvingPower > 0 && !double.IsInfinity(p.ResolvingPower));
             return new PeakSet(calculatedPeakSet);
         }
static double Utilities.PeakFinder.GetX (double yValue, double x1, double y1, double x2, double y2) static private
Gets an x value given a y value and two x,y points.
Parameters
yValue The y value for the point we want to calculate an x for.
x1 The x value of the first point in the slope.
y1 The y value of the first point in the slope.
x2 The x value of the second point in the slope.
y2 The y value of the second point in the slope.
Returns
The the calculated c value, represented as a double.
Definition at line 324 of file PeakFinder.cs.
Referenced by Utilities.PeakFinder.FindMidPoint().
         {
             /*  Point/Slope solved for X:
              *      (              (yValue - y1) )
              * x1 + ( (x2 - x1) * ---------------)
              *      (                (y2 - y1)   )
              */
             return x1 + ((x2 - x1) * ((yValue - y1) / (y2 - y1)));
         }
The documentation for this class was generated from the following file:
Falkor/Atreyu/Utilities/PeakFinder.cs