Atreyu: Viewer.ViewModels.MainWindowViewModel Class Reference
Viewer.ViewModels.MainWindowViewModel Class Reference
The main window view model.
Public Member Functions
MainWindowViewModel ()
Initializes a new instance of the MainWindowViewModel class.
Properties
CombinedHeatmapViewModel CombinedHeatmapViewModel [get, set]
Gets or sets the combined heatmap view model.
ReactiveCommand< object > ExportCompressedHeatmapData [get, set]
Gets the export compressed heatmap data.
ReactiveCommand< object > ExportCompressedMzData [get, set]
Gets the export compressed mz data.
ReactiveCommand< object > ExportCompressedTicData [get, set]
Gets the export compressed tic data.
ReactiveCommand< object > OpenFile [get, set]
Gets the open file.
ReactiveCommand< object > SaveHeatmap [get, set]
Gets the save heatmap.
Private Member Functions
async Task OpenHeatmapFile ()
The open heatmap file.
void SaveExportedHeatmapCompressedData ()
The save exported heatmap compressed data.
void SaveExportedMzCompressedData ()
The save exported mz compressed data.
void SaveExportedTicCompressedData ()
The save exported tic compressed data.
void SaveHeatmapImage ()
The save heatmap image.
Static Private Member Functions
static string GetDataFilename ()
The get data filename.
static ImageFormat GetImageFormat (string fileName)
The get image format.
Detailed Description
The main window view model.
Definition at line 46 of file MainWindowViewModel.cs.
Constructor & Destructor Documentation
Viewer.ViewModels.MainWindowViewModel.MainWindowViewModel ()
Initializes a new instance of the MainWindowViewModel class.
Definition at line 53 of file MainWindowViewModel.cs.
References Viewer.ViewModels.MainWindowViewModel.CombinedHeatmapViewModel.
         {
             this.CombinedHeatmapViewModel = new CombinedHeatmapViewModel();
             this.OpenFile = ReactiveCommand.Create();
             this.OpenFile.Select(async _ => await this.OpenHeatmapFile()).Subscribe();
             this.SaveHeatmap = ReactiveCommand.Create();
             this.SaveHeatmap.Subscribe(x => this.SaveHeatmapImage());
             this.ExportCompressedHeatmapData = ReactiveCommand.Create();
             this.ExportCompressedHeatmapData.Subscribe(x => this.SaveExportedHeatmapCompressedData());
             this.ExportCompressedMzData = ReactiveCommand.Create();
             this.ExportCompressedMzData.Subscribe(x => this.SaveExportedMzCompressedData());
             this.ExportCompressedTicData = ReactiveCommand.Create();
             this.ExportCompressedTicData.Subscribe(x => this.SaveExportedTicCompressedData());
         }
Member Function Documentation
static string Viewer.ViewModels.MainWindowViewModel.GetDataFilename () static private
The get data filename.
Returns
The string.
Definition at line 117 of file MainWindowViewModel.cs.
Referenced by Viewer.ViewModels.MainWindowViewModel.SaveExportedHeatmapCompressedData(), Viewer.ViewModels.MainWindowViewModel.SaveExportedMzCompressedData(), and Viewer.ViewModels.MainWindowViewModel.SaveExportedTicCompressedData().
         {
             const string Filter = "Comma Seperated Values (*.csv)|*.csv";
             var dialogue = new SaveFileDialog { DefaultExt = ".csv", AddExtension = true, Filter = Filter };
             var result = dialogue.ShowDialog();
             if (result != true)
             {
                 return string.Empty;
             }
             return dialogue.FileName;
         }
static ImageFormat Viewer.ViewModels.MainWindowViewModel.GetImageFormat (string fileName) static private
The get image format.
Parameters
fileName The file name.
Returns
The ImageFormat from the given extension.
Exceptions
ArgumentException Thrown is the filename passed doesn't have any extension.
NotImplementedException Thrown if an unknown extension is passed, currently bmp, gif, ico, jpg, jpeg, png, tif, tiff, and wmf are recognized.
Definition at line 147 of file MainWindowViewModel.cs.
Referenced by Viewer.ViewModels.MainWindowViewModel.SaveHeatmapImage().
         {
             var extension = Path.GetExtension(fileName);
             if (string.IsNullOrEmpty(extension))
             {
                 throw new ArgumentException(
                     string.Format("Unable to determine file extension for fileName: {0}", fileName));
             }
             switch (extension.ToLower())
             {
                 case @".bmp":
                     return ImageFormat.Bmp;
                 case @".gif":
                     return ImageFormat.Gif;
                 case @".ico":
                     return ImageFormat.Icon;
                 case @".jpg":
                 case @".jpeg":
                     return ImageFormat.Jpeg;
                 case @".png":
                     return ImageFormat.Png;
                 case @".tif":
                 case @".tiff":
                     return ImageFormat.Tiff;
                 case @".wmf":
                     return ImageFormat.Wmf;
                 default:
                     throw new NotImplementedException(
                         "The extension was not recognised, currently only  bmp, gif, ico, jpg, jpeg, png, tif, tiff, and wmf are recognized.");
             }
         }
async Task Viewer.ViewModels.MainWindowViewModel.OpenHeatmapFile () private
The open heatmap file.
Returns
The Task.
Definition at line 193 of file MainWindowViewModel.cs.
         {
             var dialogue = new OpenFileDialog
{
                                    DefaultExt = ".uimf",
                                    Filter = "Unified Ion Mobility File (*.uimf)|*.uimf"
                                };
             var result = dialogue.ShowDialog();
             if (result != true)
             {
                 return;
             }
             var filename = dialogue.FileName;
             await this.CombinedHeatmapViewModel.InitializeUimfData(filename);
         }
void Viewer.ViewModels.MainWindowViewModel.SaveExportedHeatmapCompressedData () private
The save exported heatmap compressed data.
Definition at line 216 of file MainWindowViewModel.cs.
References Viewer.ViewModels.MainWindowViewModel.GetDataFilename().
         {
             var filename = GetDataFilename();
             if (string.IsNullOrWhiteSpace(filename))
             {
                 return;
             }
             var temp = this.CombinedHeatmapViewModel.ExportHeatmapDataCompressed();
             using (var outfile = new StreamWriter(filename))
             {
                 for (var x = 0; x < temp.GetLength(0); x++)
                 {
                     var content = string.Empty;
                     for (var y = 0; y < temp.GetLength(1); y++)
                     {
                         content += temp[x, y].ToString("0.00") + ",";
                     }
                     outfile.WriteLine(content);
                 }
             }
         }
void Viewer.ViewModels.MainWindowViewModel.SaveExportedMzCompressedData () private
The save exported mz compressed data.
Definition at line 245 of file MainWindowViewModel.cs.
References Viewer.ViewModels.MainWindowViewModel.GetDataFilename().
         {
             var filename = GetDataFilename();
             if (string.IsNullOrWhiteSpace(filename))
             {
                 return;
             }
             var temp = this.CombinedHeatmapViewModel.ExportMzDataCompressed();
             using (var outfile = new StreamWriter(filename))
             {
                 var content = "mz, intensity" + Environment.NewLine;
                 foreach (var kvp in temp)
                 {
                     content += kvp.Key + "," + kvp.Value + Environment.NewLine;
                 }
                 outfile.WriteLine(content);
             }
         }
void Viewer.ViewModels.MainWindowViewModel.SaveExportedTicCompressedData () private
The save exported tic compressed data.
Definition at line 271 of file MainWindowViewModel.cs.
References Viewer.ViewModels.MainWindowViewModel.GetDataFilename().
         {
             var filename = GetDataFilename();
             if (string.IsNullOrWhiteSpace(filename))
             {
                 return;
             }
             var temp = this.CombinedHeatmapViewModel.ExportTicDataCompressed();
             using (var outfile = new StreamWriter(filename))
             {
                 var content = "scan, intensity" + Environment.NewLine;
                 foreach (var kvp in temp)
                 {
                     content += kvp.Key + "," + kvp.Value + Environment.NewLine;
                 }
                 outfile.WriteLine(content);
             }
         }
void Viewer.ViewModels.MainWindowViewModel.SaveHeatmapImage () private
The save heatmap image.
Definition at line 297 of file MainWindowViewModel.cs.
References Viewer.ViewModels.MainWindowViewModel.GetImageFormat().
         {
             const string Filter =
                 "PNG files (*.png)|*.png" + "|JPEG files (*.jpg)|*.jpg" + "|TIFF files (*.tif)|*.tif"
                 + "|Bitmaps (*.bmp)|*.bmp";
             var dialogue = new SaveFileDialog { DefaultExt = ".png", AddExtension = true, Filter = Filter };
             var result = dialogue.ShowDialog();
             if (result != true)
             {
                 return;
             }
             var image = this.CombinedHeatmapViewModel.GetImage();
             var filename = dialogue.FileName;
             var format = GetImageFormat(filename);
             image.Save(filename, format);
         }
Property Documentation
CombinedHeatmapViewModel Viewer.ViewModels.MainWindowViewModel.CombinedHeatmapViewModel get set
Gets or sets the combined heatmap view model.
Definition at line 80 of file MainWindowViewModel.cs.
Referenced by Viewer.ViewModels.MainWindowViewModel.MainWindowViewModel().
ReactiveCommand<object> Viewer.ViewModels.MainWindowViewModel.ExportCompressedHeatmapData get set
Gets the export compressed heatmap data.
Definition at line 85 of file MainWindowViewModel.cs.
ReactiveCommand<object> Viewer.ViewModels.MainWindowViewModel.ExportCompressedMzData get set
Gets the export compressed mz data.
Definition at line 90 of file MainWindowViewModel.cs.
ReactiveCommand<object> Viewer.ViewModels.MainWindowViewModel.ExportCompressedTicData get set
Gets the export compressed tic data.
Definition at line 95 of file MainWindowViewModel.cs.
ReactiveCommand<object> Viewer.ViewModels.MainWindowViewModel.OpenFile get set
Gets the open file.
Definition at line 100 of file MainWindowViewModel.cs.
ReactiveCommand<object> Viewer.ViewModels.MainWindowViewModel.SaveHeatmap get set
Gets the save heatmap.
Definition at line 105 of file MainWindowViewModel.cs.
The documentation for this class was generated from the following file:
Falkor/Atreyu/Viewer/ViewModels/MainWindowViewModel.cs