Atreyu: UimfDataExtractor.UimfProcessor Class Reference
UimfDataExtractor.UimfProcessor Class Reference
The uimf processor class handles finding and fetching data from the UIMFs.
Static Public Member Functions
static void ExtractData ()
The extract data method is the entry funtion to this process, it assumes you have set all the options already.
Properties
static CommandLineOptions Options [get, set]
Gets or sets the options.
static ConcurrentBag
< BulkPeakData > BulkMzPeaks [get, set]
Gets or sets the bulk mz peaks.
static ConcurrentBag
< BulkPeakData > BulkTicPeaks [get, set]
Gets or sets the bulk tic peaks.
static ConcurrentBag
< BulkPeakData > BulkXicPeaks [get, set]
Gets or sets the bulk xic peaks.
Static Private Member Functions
static PeakSet FindPeaks (IReadOnlyList< KeyValuePair< double, double >> dataList)
Find the peaks in the current data set and adds an annotation point with the resolution to the m/z.
static DataReader.FrameType GetFrameType (string frameType)
Gets DataReader.FrameType that corresponds with the string value.
static double[,] GetFullHeatmapData (DataReader uimf, int frameNumber)
Gets full heatmap data from the DataReader that the UIMF is open in.
static List< KeyValuePair
< double, int > > GetFullMzInfo (DataReader uimf, int frameNumber)
Gets full mass over charge info for a given frame.
static List< ScanInfo > GetFullScanInfo (DataReader uimf, int frameNumber)
Gets the Total Ion Chromatogram info for a given frame.
static List< KeyValuePair
< double, int > > GetMz (DataReader uimf, FileInfo originFile, int frameNumber)
The get mz.
static List< ScanInfo > GetTiC (DataReader uimf, FileInfo originFile, int frameNumber)
The get tic function.
static List< KeyValuePair
< double, double > > GetXic (DataReader uimf, FileInfo originFile, int frameNumber)
The get xic.
static List< KeyValuePair
< double, double > > GetXicInfo (DataReader uimf, int frameNumber, double xicMz, double tolerance, bool getMsms)
The get xic info.
static void OutputBulkPeaks ()
Outputs the bulk peaks collected during the run.
static void PrintNotFoundError (string fileOrDirectory)
Print a not found error.
static void PrintNotFoundError (FileSystemInfo fileOrDirectory)
Print a not found error.
static void ProcessAllUimfInDirectory (DirectoryInfo directory)
Process all uimf in a directory.
static void ProcessAllUimfInDirectoryRecursive (DirectoryInfo root)
Processes all uimf in directory and all the sub directories in that directory.
static void ProcessFrame (DataReader uimf, FileInfo originFile, int frameNumber=1)
Processes a single frame in a file.
static void ProcessUimf (FileInfo file)
Processes a uimf.
Static Private Attributes
static ConcurrentBag
< BulkPeakData > bulkMzPeaks
All mz peaks found in all files.
static ConcurrentBag
< BulkPeakData > bulkTicPeaks
All TiC peaks found in all files.
static ConcurrentBag
< BulkPeakData > bulkXicPeaks
All XiC peaks found in all files.
static CommandLineOptions options
The options.
Detailed Description
The uimf processor class handles finding and fetching data from the UIMFs.
Definition at line 47 of file UimfProcessor.cs.
Member Function Documentation
static void UimfDataExtractor.UimfProcessor.ExtractData () static
The extract data method is the entry funtion to this process, it assumes you have set all the options already.
Definition at line 150 of file UimfProcessor.cs.
References UimfDataExtractor.UimfProcessor.BulkMzPeaks, UimfDataExtractor.CommandLineOptions.BulkPeakComparison, UimfDataExtractor.UimfProcessor.BulkTicPeaks, UimfDataExtractor.UimfProcessor.BulkXicPeaks, UimfDataExtractor.DataExporter.InputDirectory, UimfDataExtractor.CommandLineOptions.InputPath, UimfDataExtractor.UimfProcessor.Options, UimfDataExtractor.UimfProcessor.OutputBulkPeaks(), UimfDataExtractor.CommandLineOptions.OutputPath, UimfDataExtractor.UimfProcessor.ProcessAllUimfInDirectory(), UimfDataExtractor.UimfProcessor.ProcessAllUimfInDirectoryRecursive(), UimfDataExtractor.CommandLineOptions.Recursive, and UimfDataExtractor.CommandLineOptions.Verbose.
         {
             DataExporter.InputDirectory = new DirectoryInfo(Options.InputPath);
             DataExporter.OutputDirectory = string.IsNullOrWhiteSpace(Options.OutputPath)
                                                ? DataExporter.InputDirectory
                                                : new DirectoryInfo(Options.OutputPath);
             BulkMzPeaks = new ConcurrentBag<BulkPeakData>();
             BulkTicPeaks = new ConcurrentBag<BulkPeakData>();
             BulkXicPeaks = new ConcurrentBag<BulkPeakData>();
             if (Options.Verbose)
             {
                 Console.WriteLine("Verbose Active");
                 Console.WriteLine("Input Directory: " + DataExporter.InputDirectory.FullName);
                 Console.WriteLine("Output Directory: " + DataExporter.OutputDirectory.FullName);
                 Console.WriteLine("Run Recursively?: " + Options.Recursive);
                 Console.WriteLine("Process All Frames in File?: " + Options.AllFrames);
             }
             if (Options.Recursive)
             {
                 ProcessAllUimfInDirectoryRecursive(DataExporter.InputDirectory);
             }
             else
             {
                 ProcessAllUimfInDirectory(DataExporter.InputDirectory);
             }
             if (Options.BulkPeakComparison)
             {
                 OutputBulkPeaks();
             }
             Console.WriteLine();
             Console.WriteLine("All done.");
         }
static PeakSet UimfDataExtractor.UimfProcessor.FindPeaks (IReadOnlyList< KeyValuePair< double, double >> dataList) static private
Find the peaks in the current data set and adds an annotation point with the resolution to the m/z.
Parameters
dataList The data List.
Returns
The List{T} of peaks.
Definition at line 202 of file UimfProcessor.cs.
References c, and x().
Referenced by UimfDataExtractor.UimfProcessor.GetMz(), UimfDataExtractor.UimfProcessor.GetTiC(), and UimfDataExtractor.UimfProcessor.GetXic().
         {
             var datapointList = new PeakSet();
             const int Precision = 100000;
             var peakDetector = new PeakDetector();
             var finderOptions = PeakDetector.GetDefaultSICPeakFinderOptions();
             List<double> smoothedY;
             // Create a new dictionary so we don't modify the original one
             var tempFrameList = new List<KeyValuePair<int, double>>(dataList.Count);
             // We have to give it integers, but we need the mz, so we will multiply the mz by the precision
             // and later get the correct value back by dividing it out again
             for (var i = 0; i < dataList.Count; i++)
             {
                 tempFrameList.Add(new KeyValuePair<int, double>((int)(dataList[i].Key * Precision), dataList[i].Value));
             }
             // I am not sure what this does but in the example exe file that came with the library
             // they used half of the length of the list in their previous examples and this seems to work
             var originalpeakLocation = tempFrameList.Count / 2;
             var allPeaks = peakDetector.FindPeaks(
                 finderOptions,
                 tempFrameList.OrderBy(x => x.Key).ToList(),
                 originalpeakLocation,
                 out smoothedY);
             foreach (var peak in allPeaks)
             {
                 const double Tolerance = 0.01;
                 var centerPoint = tempFrameList.ElementAt(peak.LocationIndex);
                 var offsetCenter = centerPoint.Key; // + firstpoint.Key;
                 var intensity = centerPoint.Value;
                 var smoothedPeakIntensity = smoothedY[peak.LocationIndex];
                 var realCenter = (double)offsetCenter / Precision;
                 var halfmax = smoothedPeakIntensity / 2.0;
                 var currPoint = new KeyValuePair<int, double>(0, 0);
                 var currPointIndex = 0;
                 double leftMidpoint = 0;
                 double rightMidPoint = 0;
                 var allPoints = new List<PointInformation>();
                 var leftSidePeaks = new List<KeyValuePair<int, double>>();
                 for (var l = peak.LeftEdge; l < peak.LocationIndex && l < tempFrameList.Count; l++)
                 {
                     leftSidePeaks.Add(tempFrameList[l]);
                     allPoints.Add(
                         new PointInformation
{
                                 Location = (double)tempFrameList[l].Key / Precision,
                                 Intensity = tempFrameList[l].Value,
                                 SmoothedIntensity = smoothedY[l]
                             });
                 }
                 var rightSidePeaks = new List<KeyValuePair<int, double>>();
                 for (var r = peak.LocationIndex; r < peak.RightEdge && r < tempFrameList.Count; r++)
                 {
                     rightSidePeaks.Add(tempFrameList[r]);
                     allPoints.Add(
                         new PointInformation
{
                                 Location = (double)tempFrameList[r].Key / Precision,
                                 Intensity = tempFrameList[r].Value,
                                 SmoothedIntensity = smoothedY[r]
                             });
                 }
                 // find the left side half max
                 foreach (var leftSidePeak in leftSidePeaks)
                 {
                     var prevPoint = currPoint;
                     currPoint = leftSidePeak;
                     var prevPointIndex = currPointIndex;
                     currPointIndex = tempFrameList.BinarySearch(
                         currPoint,
                         Comparer<KeyValuePair<int, double>>.Create((left, right) => left.Key - right.Key));
                     if (smoothedY[currPointIndex] < halfmax)
                     {
                         continue;
                     }
                     if (Math.Abs(smoothedY[currPointIndex] - halfmax) < Tolerance)
                     {
                         leftMidpoint = currPoint.Key;
                         continue;
                     }
                     double a1 = prevPoint.Key;
                     double a2 = currPoint.Key;
                     double c = halfmax;
                     double b1 = smoothedY[prevPointIndex];
                     double b2 = smoothedY[currPointIndex];
                     leftMidpoint = a1 + ((a2 - a1) * ((c - b1) / (b2 - b1)));
                     break;
                 }
                 // find the right side of the half max
                 foreach (var rightSidePeak in rightSidePeaks)
                 {
                     var prevPoint = currPoint;
                     currPoint = rightSidePeak;
                     var prevPointIndex = currPointIndex;
                     currPointIndex = tempFrameList.BinarySearch(
                         currPoint,
                         Comparer<KeyValuePair<int, double>>.Create((left, right) => left.Key - right.Key));
                     if (smoothedY[currPointIndex] > halfmax || smoothedY[currPointIndex] < 0)
                     {
                         continue;
                     }
                     if (Math.Abs(smoothedY[currPointIndex] - halfmax) < Tolerance)
                     {
                         rightMidPoint = currPoint.Key;
                         continue;
                     }
                     double a1 = prevPoint.Key;
                     double a2 = currPoint.Key;
                     double c = halfmax;
                     double b1 = smoothedY[prevPointIndex];
                     double b2 = smoothedY[currPointIndex];
                     rightMidPoint = a1 + ((a2 - a1) * ((c - b1) / (b2 - b1)));
                     break;
                 }
                 var correctedRightMidPoint = rightMidPoint / Precision;
                 var correctedLeftMidPoint = leftMidpoint / Precision;
                 var fullWidthHalfMax = correctedRightMidPoint - correctedLeftMidPoint;
                 var resolution = realCenter / fullWidthHalfMax;
                 var temp = new PeakInformation
{
                                    AreaUnderThePeak = peak.Area,
                                    FullWidthHalfMax = fullWidthHalfMax,
                                    Intensity = intensity,
                                    LeftMidpoint = correctedLeftMidPoint,
                                    PeakCenter = realCenter,
                                    RightMidpoint = correctedRightMidPoint,
                                    ResolvingPower = resolution,
                                    SmoothedIntensity = smoothedPeakIntensity,
                                    TotalDataPointSet = allPoints
                                };
                 if (temp.ResolvingPower > 0 && !double.IsInfinity(temp.ResolvingPower))
                 {
                     datapointList.Peaks.Add(temp);
                 }
             }
             return datapointList;
         }
static DataReader.FrameType UimfDataExtractor.UimfProcessor.GetFrameType (string frameType) static private
Gets DataReader.FrameType that corresponds with the string value.
Parameters
frameType The string value for the frame type.
Returns
The DataReader.FrameType.
Exceptions
NotImplementedException This is thrown when something other than 1, 2, 3, or 4 is passed
Definition at line 393 of file UimfProcessor.cs.
Referenced by UimfDataExtractor.UimfProcessor.GetFullMzInfo().
         {
             var temp = frameType.ToLower();
             switch (temp)
             {
                 case "1":
                     return DataReader.FrameType.MS1;
                 case "2":
                     return DataReader.FrameType.MS2;
                 case "3":
                     return DataReader.FrameType.Calibration;
                 case "4":
                     return DataReader.FrameType.Prescan;
                 default:
                     throw new NotImplementedException(
                         "Only the MS1, MS2, Calibration, and Prescan frame types have been implemented in this version. Data Passed was "
                         + temp);
             }
         }
static double [,] UimfDataExtractor.UimfProcessor.GetFullHeatmapData (DataReader uimf, int frameNumber) static private
Gets full heatmap data from the DataReader that the UIMF is open in.
Parameters
uimf The uimf that data is to be fetched from.
frameNumber The frame number that data is to be fetched.
Returns
The 2d array of doubles with the heat map data.
Definition at line 425 of file UimfProcessor.cs.
Referenced by UimfDataExtractor.UimfProcessor.ProcessFrame().
         {
             var global = uimf.GetGlobalParams();
             var endScan = uimf.GetFrameParams(frameNumber).Scans;
             var endBin = global.Bins;
             return uimf.AccumulateFrameData(frameNumber, frameNumber, false, 1, endScan, 1, endBin, 1, 1);
         }
static List<KeyValuePair<double, int> > UimfDataExtractor.UimfProcessor.GetFullMzInfo (DataReader uimf, int frameNumber) static private
Gets full mass over charge info for a given frame.
Parameters
uimf The DataReader that has the UIMF to be read.
frameNumber The frame number.
Returns
The List{T}.
Definition at line 446 of file UimfProcessor.cs.
References UimfDataExtractor.UimfProcessor.GetFrameType().
Referenced by UimfDataExtractor.UimfProcessor.GetMz().
         {
             var frameParams = uimf.GetFrameParams(frameNumber);
             var maxScans = uimf.GetFrameParams(frameNumber).Scans;
             var typeString = frameParams.GetValue(FrameParamKeyType.FrameType);
             if (string.IsNullOrWhiteSpace(typeString))
             {
                 Console.Error.WriteLine(
                     "ERROR: Had a problem getting the frame type which means we can't get the MZ data");
                 return null;
             }
             var frametype = GetFrameType(frameParams.GetValue(FrameParamKeyType.FrameType));
             double[] mzs;
             int[] intensities;
             uimf.GetSpectrum(frameNumber, frameNumber, frametype, 1, maxScans, out mzs, out intensities);
             var data = new List<KeyValuePair<double, int>>(mzs.Length);
             for (var i = 0; i < mzs.Length && i < intensities.Length; i++)
             {
                 data.Add(new KeyValuePair<double, int>(mzs[i], intensities[i]));
             }
             return data;
         }
static List<ScanInfo> UimfDataExtractor.UimfProcessor.GetFullScanInfo (DataReader uimf, int frameNumber) static private
Gets the Total Ion Chromatogram info for a given frame.
Parameters
uimf The DataReader that has the UIMF to be read.
frameNumber The frame number.
Returns
The List{T}.
Definition at line 486 of file UimfProcessor.cs.
Referenced by UimfDataExtractor.UimfProcessor.GetTiC().
         {
             return uimf.GetFrameScans(frameNumber);
         }
static List<KeyValuePair<double, int> > UimfDataExtractor.UimfProcessor.GetMz (DataReader uimf, FileInfo originFile, int frameNumber) static private
The get mz.
Parameters
uimf The uimf.
originFile The origin file.
frameNumber The frame number.
Returns
A List of Key, Value pairs, key is the m/z and the value is the intesity at that point.
Definition at line 507 of file UimfProcessor.cs.
References UimfDataExtractor.CommandLineOptions.BulkPeakComparison, UimfDataExtractor.UimfProcessor.FindPeaks(), UimfDataExtractor.UimfProcessor.GetFullMzInfo(), UimfDataExtractor.UimfProcessor.options, and UimfDataExtractor.CommandLineOptions.PeakFind.
Referenced by UimfDataExtractor.UimfProcessor.ProcessFrame().
         {
             var mzData = GetFullMzInfo(uimf, frameNumber);
             if (mzData == null)
             {
                 Console.Error.WriteLine(
                     "ERROR: We had a problem getting the data for the MZ of" + Environment.NewLine + " frame "
                     + frameNumber + " in " + originFile.FullName);
             }
             else
             {
                 var mzOutputFile = DataExporter.GetOutputLocation(originFile, "Mz", frameNumber);
                 DataExporter.OutputMz(mzData, mzOutputFile, options.Verbose);
                 if (options.PeakFind || options.BulkPeakComparison)
                 {
                     var doubleMzData =
                         mzData.Select(
                             keyValuePair => new KeyValuePair<double, double>(keyValuePair.Key, keyValuePair.Value))
                             .ToList();
                     var mzpeaks = FindPeaks(doubleMzData);
                     if (options.PeakFind)
                     {
                         var mzPeakOutputLocation = DataExporter.GetOutputLocation(
                             originFile,
                             "Mz_Peaks",
                             frameNumber,
                             "xml");
                         DataExporter.OutputPeaks(mzpeaks, mzPeakOutputLocation);
                     }
                     if (options.BulkPeakComparison)
                     {
                         foreach (var peak in mzpeaks.Peaks)
{
                             var temp = new BulkPeakData
{
                                                FileName = originFile.Name,
                                                FrameNumber = frameNumber,
                                                Location = peak.PeakCenter,
                                                FullWidthHalfMax = peak.FullWidthHalfMax,
                                                ResolvingPower = peak.ResolvingPower
                                            };
                             BulkMzPeaks.Add(temp);
                         }
                     }
                 }
             }
             return mzData;
         }
static List<ScanInfo> UimfDataExtractor.UimfProcessor.GetTiC (DataReader uimf, FileInfo originFile, int frameNumber) static private
The get tic function.
Parameters
uimf The uimf.
originFile The origin file.
frameNumber The frame number.
Returns
The List of ScanInfo.
Definition at line 575 of file UimfProcessor.cs.
References UimfDataExtractor.CommandLineOptions.BulkPeakComparison, UimfDataExtractor.UimfProcessor.FindPeaks(), UimfDataExtractor.UimfProcessor.GetFullScanInfo(), UimfDataExtractor.UimfProcessor.options, and UimfDataExtractor.CommandLineOptions.PeakFind.
Referenced by UimfDataExtractor.UimfProcessor.ProcessFrame().
         {
             var ticData = GetFullScanInfo(uimf, frameNumber);
             var ticOutputFile = DataExporter.GetOutputLocation(originFile, "TiC", frameNumber);
             DataExporter.OutputTiCbyTime(ticData, ticOutputFile, options.Verbose);
             if (options.PeakFind || options.BulkPeakComparison)
             {
                 var doubleTicData =
                     ticData.Select(scanInfo => new KeyValuePair<double, double>(scanInfo.DriftTime, scanInfo.TIC))
                         .ToList();
                 var ticPeaks = FindPeaks(doubleTicData);
                 if (options.PeakFind)
                 {
                     var mzPeakOutputLocation = DataExporter.GetOutputLocation(
                         originFile,
                         "TiC_Peaks",
                         frameNumber,
                         "xml");
                     DataExporter.OutputPeaks(ticPeaks, mzPeakOutputLocation);
                 }
                 if (options.BulkPeakComparison)
                 {
                     foreach (var peak in ticPeaks.Peaks)
                     {
                         var temp = new BulkPeakData
{
                                            FileName = originFile.Name,
                                            FrameNumber = frameNumber,
                                            Location = peak.PeakCenter,
                                            FullWidthHalfMax = peak.FullWidthHalfMax,
                                            ResolvingPower = peak.ResolvingPower
                                        };
                         BulkTicPeaks.Add(temp);
                     }
                 }
             }
             return ticData;
         }
static List<KeyValuePair<double, double> > UimfDataExtractor.UimfProcessor.GetXic (DataReader uimf, FileInfo originFile, int frameNumber) static private
The get xic.
Parameters
uimf The uimf.
originFile The origin file.
frameNumber The frame number.
Returns
The List of Key Value pairs where the Key is the scan, value is Intensity.
Definition at line 635 of file UimfProcessor.cs.
References UimfDataExtractor.CommandLineOptions.BulkPeakComparison, UimfDataExtractor.UimfProcessor.FindPeaks(), UimfDataExtractor.CommandLineOptions.Getmsms, UimfDataExtractor.CommandLineOptions.GetXiC, UimfDataExtractor.UimfProcessor.GetXicInfo(), UimfDataExtractor.UimfProcessor.options, UimfDataExtractor.CommandLineOptions.PeakFind, and UimfDataExtractor.CommandLineOptions.XicTolerance.
Referenced by UimfDataExtractor.UimfProcessor.ProcessFrame().
         {
             var xicData = GetXicInfo(uimf, frameNumber, options.GetXiC, options.XicTolerance, options.Getmsms);
             var xicOutputFile = DataExporter.GetOutputLocation(
                 originFile,
                 "XiC_mz_" + options.GetXiC + "_tolerance_" + options.XicTolerance + "_Frame",
                 frameNumber);
             if (xicData != null)
             {
                 DataExporter.OutputXiCbyTime(xicData, xicOutputFile, options.Verbose);
                 if (options.PeakFind || options.BulkPeakComparison)
                 {
                     var xicPeaks = FindPeaks(xicData);
                     if (options.PeakFind)
                     {
                         var xicPeakOutputLocation = DataExporter.GetOutputLocation(
                             originFile,
                             "XiC_Peaks_mz_" + options.GetXiC + "_tolerance_" + options.XicTolerance + "_Frame",
                             frameNumber,
                             "xml");
                         DataExporter.OutputPeaks(xicPeaks, xicPeakOutputLocation);
                     }
                     if (options.BulkPeakComparison)
                     {
                         foreach (var peak in xicPeaks.Peaks)
{
                             var temp = new BulkPeakData
{
                                                FileName = originFile.Name,
                                                FrameNumber = frameNumber,
                                                Location = peak.PeakCenter,
                                                FullWidthHalfMax = peak.FullWidthHalfMax,
                                                ResolvingPower = peak.ResolvingPower
                                            };
                             BulkXicPeaks.Add(temp);
                         }
                     }
                 }
             }
             return xicData;
         }
static List<KeyValuePair<double, double> > UimfDataExtractor.UimfProcessor.GetXicInfo (DataReader uimf, int frameNumber, double xicMz, double tolerance, bool getMsms) static private
The get xic info.
Parameters
uimf The uimf.
frameNumber The frame number.
xicMz The xic mz.
tolerance The tolerance.
getMsms The get msms.
Returns
The List of Key Value pairs where the Key is the scan, value is Intensity.
Definition at line 702 of file UimfProcessor.cs.
Referenced by UimfDataExtractor.UimfProcessor.GetXic().
         {
             const DataReader.ToleranceType Tolerance = DataReader.ToleranceType.Thomson;
             var frametype = getMsms ? DataReader.FrameType.MS2 : DataReader.FrameType.MS1;
             if (!uimf.DoesContainBinCentricData())
             {
                 Console.WriteLine(uimf.UimfFilePath + " Does not have bin centric data which is required to get XiC");
                 Console.WriteLine("starting to create it, this may take some time");
                 var fileName = uimf.UimfFilePath;
                 uimf.Dispose();
                 var dataWriter = new DataWriter(fileName);
                 dataWriter.CreateBinCentricTables();
                 dataWriter.Dispose();
                 uimf = new DataReader(fileName);
                 Console.WriteLine("Finished Creating bin centric tables for " + uimf.UimfFilePath);
             }
             List<IntensityPoint> xic;
             try
             {
                 xic = uimf.GetXic(xicMz, tolerance, frametype, Tolerance);
             }
             catch (Exception)
             {
                 Console.Error.WriteLine("Unable to get XiC on first attempt for " + uimf.UimfFilePath);
                 var tempreader = new DataReader(uimf.UimfFilePath);
                 try
                 {
                     xic = tempreader.GetXic(xicMz, tolerance, frametype, Tolerance);
                 }
                 catch (Exception)
                 {
                     Console.Error.WriteLine(
                         "Unable to get XiC on second attempt for " + uimf.UimfFilePath + ", we are not trying again.");
                     return null;
                 }
             }
             var frameData = xic.Where(point => point.ScanLc == frameNumber - 1);
             var data = new List<KeyValuePair<double, double>>();
             foreach (var intensityPoint in frameData)
             {
                 var driftTime = uimf.GetDriftTime(intensityPoint.ScanLc + 1, intensityPoint.ScanIms, true);
                 data.Add(new KeyValuePair<double, double>(driftTime, intensityPoint.Intensity));
             }
             return data;
         }
static void UimfDataExtractor.UimfProcessor.OutputBulkPeaks () static private
Outputs the bulk peaks collected during the run.
Definition at line 766 of file UimfProcessor.cs.
References UimfDataExtractor.UimfProcessor.BulkMzPeaks, UimfDataExtractor.UimfProcessor.BulkTicPeaks, UimfDataExtractor.UimfProcessor.BulkXicPeaks, UimfDataExtractor.CommandLineOptions.GetMz, UimfDataExtractor.CommandLineOptions.GetTiC, UimfDataExtractor.CommandLineOptions.GetXiC, and UimfDataExtractor.UimfProcessor.options.
Referenced by UimfDataExtractor.UimfProcessor.ExtractData().
         {
             var dateString = DateTime.Now.ToString("yyyyMMdd-HHmmss");
             var inputFolder = DataExporter.InputDirectory.Name;
             if (options.GetMz)
             {
                 DataExporter.OutputBulkMzPeakData(dateString, inputFolder, BulkMzPeaks);
             }
             if (options.GetTiC)
             {
                 DataExporter.OutputBulkTicPeakData(dateString, inputFolder, BulkTicPeaks);
             }
             if (options.GetXiC > 0)
             {
                 DataExporter.OutputBulkXicPeakData(
                     dateString,
                     inputFolder,
                     BulkXicPeaks,
                     options.GetXiC,
                     options.XicTolerance);
             }
         }
static void UimfDataExtractor.UimfProcessor.PrintNotFoundError (string fileOrDirectory) static private
Print a not found error.
Parameters
fileOrDirectory The file or directory.
Definition at line 799 of file UimfProcessor.cs.
Referenced by UimfDataExtractor.UimfProcessor.ProcessAllUimfInDirectory(), UimfDataExtractor.UimfProcessor.ProcessAllUimfInDirectoryRecursive(), and UimfDataExtractor.UimfProcessor.ProcessUimf().
         {
             Console.WriteLine();
             Console.WriteLine(fileOrDirectory + "does not exist");
             Console.WriteLine();
         }
static void UimfDataExtractor.UimfProcessor.PrintNotFoundError (FileSystemInfo fileOrDirectory) static private
Print a not found error.
Parameters
fileOrDirectory The file or directory.
Definition at line 812 of file UimfProcessor.cs.
         {
             Console.WriteLine();
             Console.WriteLine(fileOrDirectory.FullName + "does not exist");
             Console.WriteLine();
         }
static void UimfDataExtractor.UimfProcessor.ProcessAllUimfInDirectory (DirectoryInfo directory) static private
Process all uimf in a directory.
Parameters
directory The directory to process.
Definition at line 825 of file UimfProcessor.cs.
References UimfDataExtractor.UimfProcessor.options, UimfDataExtractor.UimfProcessor.PrintNotFoundError(), UimfDataExtractor.UimfProcessor.ProcessUimf(), and UimfDataExtractor.CommandLineOptions.Verbose.
Referenced by UimfDataExtractor.UimfProcessor.ExtractData(), and UimfDataExtractor.UimfProcessor.ProcessAllUimfInDirectoryRecursive().
         {
             if (directory.Exists)
             {
                 if (options.Verbose)
                 {
                     Console.WriteLine("Starting to process UIMFs in " + directory.FullName);
                 }
                 var uimfs = directory.EnumerateFiles("*.uimf");
                 Parallel.ForEach(uimfs, ProcessUimf);
             }
             else
             {
                 PrintNotFoundError(directory);
             }
         }
static void UimfDataExtractor.UimfProcessor.ProcessAllUimfInDirectoryRecursive (DirectoryInfo root) static private
Processes all uimf in directory and all the sub directories in that directory.
Parameters
root The root to start at.
Definition at line 850 of file UimfProcessor.cs.
References UimfDataExtractor.UimfProcessor.options, UimfDataExtractor.UimfProcessor.PrintNotFoundError(), UimfDataExtractor.UimfProcessor.ProcessAllUimfInDirectory(), and UimfDataExtractor.CommandLineOptions.Verbose.
Referenced by UimfDataExtractor.UimfProcessor.ExtractData().
         {
             if (root.Exists)
             {
                 if (options.Verbose)
                 {
                     Console.WriteLine("Started recursive work in " + root.FullName);
                 }
                 ProcessAllUimfInDirectory(root);
                 Parallel.ForEach(root.EnumerateDirectories(), ProcessAllUimfInDirectoryRecursive);
             }
             else
             {
                 PrintNotFoundError(root);
             }
         }
static void UimfDataExtractor.UimfProcessor.ProcessFrame (DataReader uimf, FileInfo originFile, int frameNumber = 1) static private
Processes a single frame in a file.
Parameters
uimf The uimf.
originFile The origin file (we need to keep track o it for saving purposes) .
frameNumber The frame number.
Definition at line 883 of file UimfProcessor.cs.
References UimfDataExtractor.UimfProcessor.GetFullHeatmapData(), UimfDataExtractor.CommandLineOptions.GetHeatmap, UimfDataExtractor.CommandLineOptions.GetMz, UimfDataExtractor.UimfProcessor.GetMz(), UimfDataExtractor.CommandLineOptions.GetTiC, UimfDataExtractor.UimfProcessor.GetTiC(), UimfDataExtractor.CommandLineOptions.GetXiC, UimfDataExtractor.UimfProcessor.GetXic(), UimfDataExtractor.UimfProcessor.options, and UimfDataExtractor.CommandLineOptions.Verbose.
Referenced by UimfDataExtractor.UimfProcessor.ProcessUimf().
         {
             // eventually I will also have methods for mz and heatmap,
             var frameParams = uimf.GetFrameParams(frameNumber);
             if (frameParams == null)
             {
                 // Frame number is out of range
                 Console.WriteLine();
                 Console.Error.WriteLine(
                     "ERROR: Somehow a frame number that doesn't exist was attempted to read" + Environment.NewLine
                     + "So we are not creating data for frame " + frameNumber + " Of " + Environment.NewLine
                     + originFile.FullName);
                 Console.WriteLine();
                 return;
             }
             if (options.GetHeatmap)
             {
                 var heatmapData = GetFullHeatmapData(uimf, frameNumber);
                 var heatmapOutputFile = DataExporter.GetOutputLocation(originFile, "HeatMap", frameNumber);
                 DataExporter.OutputHeatMap(heatmapData, heatmapOutputFile, options.Verbose);
             }
             if (options.GetMz)
             {
                 GetMz(uimf, originFile, frameNumber);
             }
             if (options.GetTiC)
             {
                 GetTiC(uimf, originFile, frameNumber);
             }
             if (options.GetXiC > 0)
             {
                 GetXic(uimf, originFile, frameNumber);
             }
             if (options.Verbose)
             {
                 Console.WriteLine("Finished processing Frame " + frameNumber + " of " + originFile.FullName);
             }
         }
static void UimfDataExtractor.UimfProcessor.ProcessUimf (FileInfo file) static private
Processes a uimf.
Parameters
file The file to process.
Definition at line 935 of file UimfProcessor.cs.
References UimfDataExtractor.CommandLineOptions.AllFrames, UimfDataExtractor.UimfProcessor.options, UimfDataExtractor.UimfProcessor.PrintNotFoundError(), UimfDataExtractor.UimfProcessor.ProcessFrame(), and UimfDataExtractor.CommandLineOptions.Verbose.
Referenced by UimfDataExtractor.UimfProcessor.ProcessAllUimfInDirectory().
         {
             if (!file.Exists)
             {
                 PrintNotFoundError(file);
                 return;
             }
             using (var uimfReader = new DataReader(file.FullName))
             {
                 if (options.Verbose)
                 {
                     Console.WriteLine("Starting to process " + file.FullName);
                 }
                 var framecount = uimfReader.GetGlobalParams().NumFrames;
                 if (options.AllFrames)
                 {
                     // ReSharper disable once AccessToDisposedClosure
                     for (var i = 0; i <= framecount; i++)
                     {
                         ProcessFrame(uimfReader, file, i);
                     }
                 }
                 else
                 {
                     ProcessFrame(uimfReader, file);
                 }
             }
             Console.WriteLine("Finished processing " + file.FullName);
         }
Member Data Documentation
ConcurrentBag<BulkPeakData> UimfDataExtractor.UimfProcessor.bulkMzPeaks static private
All mz peaks found in all files.
Definition at line 54 of file UimfProcessor.cs.
ConcurrentBag<BulkPeakData> UimfDataExtractor.UimfProcessor.bulkTicPeaks static private
All TiC peaks found in all files.
Definition at line 59 of file UimfProcessor.cs.
ConcurrentBag<BulkPeakData> UimfDataExtractor.UimfProcessor.bulkXicPeaks static private
All XiC peaks found in all files.
Definition at line 64 of file UimfProcessor.cs.
CommandLineOptions UimfDataExtractor.UimfProcessor.options static private
The options.
Definition at line 69 of file UimfProcessor.cs.
Referenced by UimfDataExtractor.UimfProcessor.GetMz(), UimfDataExtractor.UimfProcessor.GetTiC(), UimfDataExtractor.UimfProcessor.GetXic(), UimfDataExtractor.UimfProcessor.OutputBulkPeaks(), UimfDataExtractor.UimfProcessor.ProcessAllUimfInDirectory(), UimfDataExtractor.UimfProcessor.ProcessAllUimfInDirectoryRecursive(), UimfDataExtractor.UimfProcessor.ProcessFrame(), and UimfDataExtractor.UimfProcessor.ProcessUimf().
Property Documentation
ConcurrentBag<BulkPeakData> UimfDataExtractor.UimfProcessor.BulkMzPeaks static get set private
Gets or sets the bulk mz peaks.
Definition at line 99 of file UimfProcessor.cs.
Referenced by UimfDataExtractor.UimfProcessor.ExtractData(), and UimfDataExtractor.UimfProcessor.OutputBulkPeaks().
ConcurrentBag<BulkPeakData> UimfDataExtractor.UimfProcessor.BulkTicPeaks static get set private
Gets or sets the bulk tic peaks.
Definition at line 115 of file UimfProcessor.cs.
Referenced by UimfDataExtractor.UimfProcessor.ExtractData(), and UimfDataExtractor.UimfProcessor.OutputBulkPeaks().
ConcurrentBag<BulkPeakData> UimfDataExtractor.UimfProcessor.BulkXicPeaks static get set private
Gets or sets the bulk xic peaks.
Definition at line 131 of file UimfProcessor.cs.
Referenced by UimfDataExtractor.UimfProcessor.ExtractData(), and UimfDataExtractor.UimfProcessor.OutputBulkPeaks().
CommandLineOptions UimfDataExtractor.UimfProcessor.Options static get set
Gets or sets the options.
Definition at line 79 of file UimfProcessor.cs.
Referenced by UimfDataExtractor.UimfProcessor.ExtractData(), and UimfDataExtractor.Program.Main().
The documentation for this class was generated from the following file:
Falkor/Atreyu/UIMF Data Extractor/UimfProcessor.cs